### ISSUE TITLE
Slight home page adjustments

### ISSUE THREAD

**Issue by Richenda** [rtcharity/hubreboot#104]
1: Switch the place of 'EA Work and Volunteering' and 'EA Donation Swap'.
2: The banner image within the header should move slightly down so that it appears to be more centrally placed in the header (along the vertical axis).

**Comment by sebgrebe** [comment]
Implemented
[Commit1](https://github.com/rtcharity/hubreboot/commit/d6470c02a9753d88e9366cf6eb253b59e03f6c59)
[Commit2](https://github.com/rtcharity/hubreboot/commit/8e27a00f00f710c748e278ce10eb50be91d2d344)
