### ISSUE TITLE
Randomise profile avatars

### ISSUE THREAD

**Issue by sebgrebe** [rtcharity/hubreboot#107]
as suggested by Richenda [here](https://github.com/rtcharity/hubreboot/issues/97#issuecomment-453927284)

**Comment by Richenda** [comment]
What's going on with this @Manoj-nathwani ?

**Comment by Manoj-nathwani** [comment]
Seb built it a while ago however we've now completely changed how avatars work so his update never went live. I'll have to re-do it on the backend instead 👌 

@Richenda - can you send me a link to all the images you want to use please 🙏

**Comment by Richenda** [comment]
Oh, I see.
Here are the images to include: https://drive.google.com/open?id=1hC8NKcdapjAiuwmgo_ztS9webQAJrZjd

You might also want to consider this issue at the same time: https://github.com/rtcharity/hubreboot/issues/232

**Comment by Manoj-nathwani** [comment]
- Perfect thanks :)
- Yep, that's a different issue though so we'll discuss that there

**Comment by Manoj-nathwani** [comment]
Done ✅ 
https://github.com/rtcharity/hubreboot/commit/397eaad00ca52887c52bf23866fd711adc999afc

**Comment by Richenda** [comment]
Eek! This is awesome!
