### ISSUE TITLE
Choose backend(s) for MVP

### ISSUE THREAD

**Issue by taymonbeal** [rtcharity/hubreboot#11]
The current dev.eahub.org is in WordPress without any custom code, but we need to figure out whether it'll stay that way, or what.

All currently required MVP functions can be handled by anything that can display static content, except for editable profiles. We have the Ultimate Member plugin, but its technical suitability has not yet been investigated. Future features may require more custom code.

**Comment by taymonbeal** [comment]
Blocked on #8.

**Comment by herwix** [comment]
I also had an interesting talk with David about Wordpress. So what came out of this discussion is that our architecture/plan is very much driven by what we want the eahub to be in the long run. 

If it is supposed to become a central points for EAs to search important sources and data (e.g., job listings, articles from the forum, personal or group profiles, etc.), it would make sense to go for something like a modular architecture I outlined before where we have a light backend service scraping/integrating websites and aggregating data into our search service which is then called by a (custom) search front end. In this case EA profiles would simply be treated like any other interesting EA website that we want to integrate. We could run it on wordpress or whatever seems plausible. However, this overall approach is somewhat developer intensive as we need to keep the integration with other websites running.

If that's too ambitious and the goal is to stay with basic profiles, the resource trail, and simple links to the other platforms (instead of integrating them into our search). Then something like Wordpress for everything would probably make a lot of sense, as it would be easier to keep running due to all the plugins and support available in the WP community.

A combination of both approaches also seems plausible (2 for MVP and 1 for later) if strategically desired.

So this seems to be an important question that needs to be answered.

**Comment by taymonbeal** [comment]
Okay, this gives me a better picture of what you meant by "modular architecture". I quite agree that it sounds intensive in terms of developer support. Maintaining our own databases is very likely to be simpler and I think we should prefer to do it if at all possible. Of course, if we find we need to integrate data that some other org owns, then we have to do something like this; the exact technical details of how it should work would depend on what kind of technical resources the other org has and what kind of access they're comfortable with our systems having.

As far as the MVP goes, if I understand the requirements correctly, most site functions will depend only manually curated and maintained data, so the choice of backend is mostly irrelevant; we can use anything that provides static-site functionality. (In some ways it would be nicer if the content lived in Git, but that's not a hard requirement.) The one major exception is user profiles, which users need to be able to create and edit without involvement from trusted humans.

We still haven't assessed the technical suitability of the Ultimate Member plugin for this purpose. My guess, having not actually seen it for myself, is that it will not offer much flexibility in terms of database schema, so we need to check whether the data we're going to import will fit in the schema it does offer. That's blocked on #4.

If Ultimate Member doesn't work, then we probably need to choose some kind of backend solution that allows us to write our own data schema. Options I'm familiar with for doing this with a minimum of code include Django and Firebase. We could also write our own WordPress plugin, but I fear the developer experience will be painful. Another option is Vulcan.js, which is less mainstream and in some respects more operationally complex, but which the EA community is already invested in technical expertise around, as it is the basis for LessWrong. People familiar with other backend stacks that they think would work well should comment here.

The other question is how to integrate the backend with the frontend. Possibilities in order of increasing maintenance burden:
1. Only one backend renders HTML. All others, if they exist, are communicated with via AJAX requests. This is where we'll be if we use WordPress for everything, or Django for everything, or a static site generator plus Firebase. (Technically we could also use WordPress or Django plus Firebase, but that seems needlessly operationally burdensome.)
2. Multiple backends render HTML but they share common templates and CSS. This is where we'll be if we use Django plus a static site generator.
3. Multiple backends render HTML with their own distinct templates, but we keep the code in sync at all times. This is where we'll be if we use WordPress plus a static site generator.

**Comment by herwix** [comment]
> Okay, this gives me a better picture of what you meant by "modular architecture". I quite agree that it sounds intensive in terms of developer support. Maintaining our own databases is very likely to be simpler and I think we should prefer to do it if at all possible.

Could you clarify what you mean by this? In the modular model we could use the search index (Algolia) as our main database. We could also keep a DB running just to be save but the main idea would be to have a slim/simple data layer which is outside of wordpress and powers our search.  What do you mean exactly with "Maintaining our own databases is very likely to be simpler and I think we should prefer to do it if at all possible." in this context?

> As far as the MVP goes, if I understand the requirements correctly, most site functions will depend only manually curated and maintained data, so the choice of backend is mostly irrelevant; we can use anything that provides static-site functionality. (In some ways it would be nicer if the content lived in Git, but that's not a hard requirement.) The one major exception is user profiles, which users need to be able to create and edit without involvement from trusted humans.

Generally I very much agree but afaik there is also a need to create/list local EA groups/chapters? Not that it would change much in how we would approach this but just to be clear about the requirements.

> We still haven't assessed the technical suitability of the Ultimate Member plugin for this purpose. My guess, having not actually seen it for myself, is that it will not offer much flexibility in terms of database schema, so we need to check whether the data we're going to import will fit in the schema it does offer. That's blocked on #4.

Totally agree, that should be investigated and thought about. It ties directly to the first point, what kind of data storage/db do we want for user/group profile data and can we get it in a reasonable format with the WP plugin? There are a few hundred tables right now, we should look to make this much more manageable in the future.

> If Ultimate Member doesn't work, then we probably need to choose some kind of backend solution that allows us to write our own data schema. Options I'm familiar with for doing this with a minimum of code include Django and Firebase. We could also write our own WordPress plugin, but I fear the developer experience will be painful. Another option is Vulcan.js, which is less mainstream and in some respects more operationally complex, but which the EA community is already invested in technical expertise around, as it is the basis for LessWrong. People familiar with other backend stacks that they think would work well should comment here.

I come more from the JVM side so my experience is more with stuff like [Grails](https://grails.org/), which is similar to Ruby on Rails or Django. [Vert.x](https://vertx.io/) would be another JVM based alternative or plain old Spring Boot. I don't know if Firebase would be the best option giving the potential cost for ongoing use but it seems to be pretty popular. I would really not want to go down the route of a WP plugin if the one that was bought doesn't work for our purposes. That's imho like the maximum on overhead and complexity we could get without the benefits of the Wordpress community. Vulcan seems interesting from a technological point of view and something that may be fun for developers to get into but you are certainly right, not mainstream. Something more mainstream would be a simple node.js and express set up.

Anyhow getting something like profiles going would be easy to set up in any reasonable backend. It's just CRUD with some nice styling and maybe some admin views.

 > The other question is how to integrate the backend with the frontend. Possibilities in order of increasing maintenance burden:

1. Only one backend renders HTML. All others, if they exist, are communicated with via AJAX requests. This is where we'll be if we use WordPress for everything, or Django for everything, or a static site generator plus Firebase. (Technically we could also use WordPress or Django plus Firebase, but that seems needlessly operationally burdensome.)
2. Multiple backends render HTML but they share common templates and CSS. This is where we'll be if we use Django plus a static site generator.
3. Multiple backends render HTML with their own distinct templates, but we keep the code in sync at all times. This is where we'll be if we use WordPress plus a static site generator.

I think you have missed another possible option, which could be having one (or multiple) front-end apps (e.g., react) that talks to one (or multiple) backends. If we have something like node.js with server side rendering that may be the same as what you suggested. While I think that this is overkill for the static content or the profile pages, I do think it could make sense for the search, depending on how sophisticated we want to make it over time.
