### ISSUE TITLE
Feature icons on homepage

### ISSUE THREAD

**Issue by sebgrebe** [rtcharity/hubreboot#115]
Marcin suggests: 
1. "Should we replace the icon for EA Resources with something more suggestive of a structured repository of knowledge?"
2. "Could we use a higher-resolution picture in the EA Swap section and improve its formatting, making it consistent with the rest of the Hub?"
https://docs.google.com/spreadsheets/d/1qotdbleP9NHHieVsFkO2LQ6qeI43wBF2P0m_2NOe-xw/edit?ts=5c43311d#gid=0

**Comment by sebgrebe** [comment]
@Richenda Thoughts? If you don't think that's necessary, close the ticket. 
If you think that should be done but not priority before launch, move the card to the non-priority column

**Comment by Richenda** [comment]
@marcinkowrygo nothing in the EA Swap area is anything we can do for this launch. It is an entirely different website made by EA New Zealand that we did not set up. At some point I would love for the Rethink team to redo it from scratch but at the moment we have no control or access to what it looks like and it's not a priority.

 For the feature icons, no there aren't any other images that can be used from existing designed ones. I don't have time to design a new image from scratch (also I don't want to) but if everybody feels strongly about it, come back to me about it for later versions. Also please remember that this was designed for the 'Resource Trail', and that is a set of feet on a 'trail'. The decision to remove 'trail' from 'resources' wasn't made when this design was illustrated.
