### ISSUE TITLE
Add About page

### ISSUE THREAD

**Issue by sebgrebe** [rtcharity/hubreboot#116]

**Comment by sebgrebe** [comment]
I've added a very basic [about page](https://eahub.azurewebsites.net/about/)

@michaltrzesimiech The content needs updating, as I've just copied from the resources page. I'd take you up on your offer to re-write the content :)

@Richenda Let me know your thoughts on design.

The two contact buttons are currently just 'mailto' links. If you'd like, I could implement the [forms we currently have on the resources page](https://resources.eahub.org/contact-tech/). Notice though that these run on zapier, if we go beyond 100 mails per month it costs us money

**Comment by Richenda** [comment]
>I propose we just use the one from EA Resources page and remove it there.

> @Richenda you're cool with that ?

Well that is what I directly asked for a few weeks ago :p

**Comment by Richenda** [comment]
>The two contact buttons are currently just 'mailto' links. If you'd like, I could implement the forms  we currently have on the resources page. Notice though that these run on zapier, if we go beyond 100 mails per month it costs us money

Is there any free way for links that just open up the person's default mail service and start a new email?

**Comment by sebgrebe** [comment]
> > The two contact buttons are currently just 'mailto' links. If you'd like, I could implement the forms  we currently have on the resources page. Notice though that these run on zapier, if we go beyond 100 mails per month it costs us money
> 
> Is there any free way for links that just open up the person's default mail service and start a new email?

That's what mailto does!

**Comment by Richenda** [comment]
Regarding the copy of the About page, I am still fine with most of it except that we need to delete the line about announcing it in 2018. The one thing I want to expand is the last section 'Planned features' with a blurb about the Hub being a permanent beta and that we have in mind to work on a project feature and a survey dashboard.

I think the page looks slightly bare now that I asked us to remove the banner image. So lets put a small image at the bottom of the text: https://drive.google.com/open?id=1rnF0nmJZryzfAuknyRZaxeZjjPW-xHyx or https://drive.google.com/open?id=1KVPBk8FdHF5gSl7mCt1zXi1iNVrTg6uj

**Comment by Richenda** [comment]
> Is there any free way for links that just open up the person's default mail service and start a new email?
> 
> That's what mailto does!

Ok cool but then why do we have to worry about a fee? Sorry...

**Comment by michaltrzesimiech** [comment]
Draft for the "About" page content https://docs.google.com/document/d/1DtKj3oD5j18kXh3TGVi84-YDmMNI_my6GQLw8NcR6wg/edit

**Comment by sebgrebe** [comment]
@michaltrzesimiech Thanks! I've requested access.

**Comment by sebgrebe** [comment]
> > Is there any free way for links that just open up the person's default mail service and start a new email?
> > That's what mailto does!
> 
> Ok cool but then why do we have to worry about a fee? Sorry...

Sorry, I think I wasn't clear enough: On the resources page, we currently have forms people can fill out. That costs money > 100 emails. On the hub, we have mailto-links instead, which simply open up the users email service, with a draft email to LEAN or RTCharity. If the latter solution is fine, I'd prefer to stick with this (it's already done, and there is other stuff I have to do :) )

**Comment by sebgrebe** [comment]
> Regarding the copy of the About page, I am still fine with most of it except that we need to delete the line about announcing it in 2018. The one thing I want to expand is the last section 'Planned features' with a blurb about the Hub being a permanent beta and that we have in mind to work on a project feature and a survey dashboard.
> 
> I think the page looks slightly bare now that I asked us to remove the banner image. So lets put a small image at the bottom of the text: https://drive.google.com/open?id=1rnF0nmJZryzfAuknyRZaxeZjjPW-xHyx or https://drive.google.com/open?id=1KVPBk8FdHF5gSl7mCt1zXi1iNVrTg6uj

@Richenda Thanks for the feedback, will do

**Comment by Richenda** [comment]
> > > Is there any free way for links that just open up the person's default mail service and start a new email?
> > > That's what mailto does!
> > 
> > 
> > Ok cool but then why do we have to worry about a fee? Sorry...
> 
> @Richenda
> 
> Sorry, I think I wasn't clear enough: On the resources page, we currently have forms people can fill out. That costs money > 100 emails. On the hub, we have mailto-links instead, which simply open up the users email service, with a draft email to LEAN or RTCharity. If the latter solution is fine, I'd prefer to stick with this (it's already done, and there is other stuff I have to do :) )
@sebgrebe great then we have the same preferences here.

Regarding content in the About page, me and @michaltrzesimiech are figuring this out together right now.

**Comment by sebgrebe** [comment]
@Richenda and @michaltrzesimiech Thanks for the text, I've added it. Let me know when you're completely happy with it (I think Richenda isn't fully done yet), and I'll update the text

**Comment by Manoj-nathwani** [comment]
Marking as complete as it's been a week now. If there's further updates needed we can make a new card for the updates they want ✅
