### ISSUE TITLE
Profile model

### ISSUE THREAD

**Issue by sebgrebe** [rtcharity/hubreboot#119]
https://github.com/rtcharity/hubreboot/issues/39#issuecomment-453843775

**Comment by Manoj-nathwani** [comment]
See original card for notes

**Comment by Manoj-nathwani** [comment]
# All done ✅ 
- Code: https://github.com/rtcharity/hubreboot/commit/0cfaf9b59c356cd61e079416fcb210c35b71b431
- Wired up all new fields to the backend
- Removed `info` as it was redundant
- Removed `direct_work_hours` as I wasn't sure what it meant and we can figure out what it should mean in the future
