### ISSUE TITLE
Add logout function

### ISSUE THREAD

**Issue by sebgrebe** [rtcharity/hubreboot#120]
[Pointed out](https://docs.google.com/spreadsheets/d/1qotdbleP9NHHieVsFkO2LQ6qeI43wBF2P0m_2NOe-xw/edit?ts=5c43311d#gid=0) by Marcin.

**Comment by Manoj-nathwani** [comment]
All sorted https://github.com/rtcharity/hubreboot/commit/27a0d1ff0454ea365e06e26e0c8d9e3a3a8c51a6
