### ISSUE TITLE
Add cookie banner

### ISSUE THREAD

**Issue by sebgrebe** [rtcharity/hubreboot#121]
If necessary. Probably because we're using Google Analytics

**Comment by sebgrebe** [comment]
@michaltrzesimiech From a legal/privacy perspective, do we need a cookie banner?

**Comment by michaltrzesimiech** [comment]
Yep, we need a cookie banner for GDPR reasons!

**Comment by taymonbeal** [comment]
The cookie banner is just for Google Analytics, right? It doesn't need to be connected to anything else? I don't usually see sites displaying a cookie banner in order for users to log in.

**Comment by sebgrebe** [comment]
There are 3 different options for banners: info, opt-in, and opt-out. Went for info as it should be sufficient: "We cannot guarantee an informational approach will be sufficient for your website, but unless you have special cause to believe otherwise, it is extremely likely. If in doubt, seek legal advice from a professional."
https://cookieconsent.insites.com/documentation/compliance/
