### ISSUE TITLE
Big security check

### ISSUE THREAD

**Issue by sebgrebe** [rtcharity/hubreboot#122]
We should have a security checklist that we go through before the release. This should include GDPR/privacy issues.

**Comment by Manoj-nathwani** [comment]
See recent update to how we're protecting users privacy: https://github.com/rtcharity/hubreboot/issues/126

# Our attitude towards data
- All data given to the hub is made public, excluding your email address & password
- To respect users privacy & GDPR we've hidden all personal information until users log into their accounts and review their profile.
- I've also removed exact map coordinates of users and we're sticking with just their town/city & country as a higher resolution isn't needed.

# Questions for @michaltrzesimiech 
- Are we correct assuming all information saved on the hub should be public?
- We can't imagine cases where users would add data to their profile which they didn't want to share with others, that's what Sebatian & I concluded the other day.

**Comment by michaltrzesimiech** [comment]
I'm speaking with the person behind http://sakure.co to see whether we could have some automated checks running continuously.

**Comment by Manoj-nathwani** [comment]
cc @taymonbeal,
This may be something you want to give input on

**Comment by michaltrzesimiech** [comment]
Check by sakure.io found no new issues and will monitor things continuously. Closing the issue.
