### ISSUE TITLE
GDPR Audit

### ISSUE THREAD

**Issue by Manoj-nathwani** [rtcharity/hubreboot#126]
# What's wrong?
- Users put a lot of private data into the old hub
- It's been several years since some put their data in
- [GDPR](https://eugdpr.org) has also recently come into play too
- **Making sure we respect our users privacy is super important**

# Data we store on users
- username
- email address (never shared publicly)
- city_or_town
- country

# What we've done
![](https://i.imgur.com/Fch5kOg.jpg)
![](https://i.imgur.com/3BMGMPW.jpg)

**Comment by michaltrzesimiech** [comment]
Perfect! Let's go with that, thanks!

**Comment by Manoj-nathwani** [comment]
# Update to usernames:
![](https://i.imgur.com/4SfgKCY.png)

**Comment by Manoj-nathwani** [comment]
@Richenda We still need a redesign of this image as I kinda just stole it off google search 😅 

![image](https://user-images.githubusercontent.com/2634482/52000409-f125a480-24b4-11e9-9276-e5753e4abfb7.png)

**Comment by sebgrebe** [comment]
@Manoj-nathwani Working on this now.

Clarification: Are we all d'accord that we can display usernames of people who haven't GDPR confirmed yet? I thought there was some push back on this, because usernames could potentially be personal information, too. We could instead just completely hide someone on the list.

@michaltrzesimiech ?

**Comment by michaltrzesimiech** [comment]
We should be fine for now as long as nobody raises an objection when we're in silent launch mode. Let's keep this issue open and revisit the decision before the official launch.

**Comment by michaltrzesimiech** [comment]
The rationale is that users put their data on their own before, we're just resurfacing it. Before the official launch, we will ask each and every user to review their details (and give them the option to delete their data permanently).

**Comment by Manoj-nathwani** [comment]
yeah exactly. We're going a pretty big extra mile to hide things because we're aware they gave us permission a long long time ago.

**Comment by Manoj-nathwani** [comment]
Closing issue as the banner has it's own card https://github.com/rtcharity/hubreboot/issues/139
