### ISSUE TITLE
Clear database

### ISSUE THREAD

**Issue by sebgrebe** [rtcharity/hubreboot#130]
Before launch, make sure to delete any test profiles and groups we have created during development.
* groups: 700-705
* Profiles: 14020

**Comment by sebgrebe** [comment]
@Manoj-nathwani can we now delete groups? If not, people should make a list of groups they've created so that you or Taymon could delete them directly from the database.

**Comment by sebgrebe** [comment]
@michaltrzesimiech @Richenda @Manoj-nathwani @marcin-wosinek @taymonbeal 
Please create any test profiles you might have created during development

**Comment by Richenda** [comment]
I'm confused, sorry :p Is the point to (a) ask us to do some testing (b) replicate any test accounts so that it's identical to how it was a few days ago? (c) get rid of dupe accounts?

**Comment by taymonbeal** [comment]
We'll fix this by just deleting all the accounts, since we won't have migrated data.

**Comment by Manoj-nathwani** [comment]
Profiles have been flushed ✅

**Comment by sebgrebe** [comment]
> Profiles have been flushed ✅

Cool. Man, there's been a lot of changes over the last couple of days 😄
