### ISSUE TITLE
Privacy policy

### ISSUE THREAD

**Issue by Manoj-nathwani** [rtcharity/hubreboot#131]
# Problem
@arichard4 very well noted that we need a **privacy statement** and user sign up workflow which requires users to acknowledge that they have read, understood and agree to our use of their data

# Solution
1) Add a privacy policy checkbox on the `/profile/edit` & `/group/123/edit` pages

![](https://i.imgur.com/X4GXChR.png) 

2) Get Michael/Richenda to sort out exactly what the statement should include

# Notes
- Required before launch ❗️

**Comment by taymonbeal** [comment]
Is it actually a regulatory requirement that we make users say they read it (even though they almost certainly didn't)?

**Comment by Manoj-nathwani** [comment]
Pretty sure it is as they're giving us personal data
I'm happy sticking to industry standards for this and having a regular checkbox.

**Comment by Richenda** [comment]
We're sticking with the standard.
@michaltrzesimiech can I delegate the writing of a terms and conditions to LEAN?

**Comment by michaltrzesimiech** [comment]
Sure thing, I already took this on to my list. Thanks!

**Comment by michaltrzesimiech** [comment]
There's a draft in here https://docs.google.com/document/d/1MplKLlCiGK8mTxnp-3adbbYqQELchUyc9akjshII0Zg/edit?usp=sharing

**Comment by Richenda** [comment]
@michaltrzesimiech if I could have commenting access that would be cool.

**Comment by michaltrzesimiech** [comment]
The policy is ready and available under that address

**Comment by Manoj-nathwani** [comment]
@sebgrebe sorry for the late reply!
Providing you can only submit the form if you check the box then yes - you're good to merge this and deploy :) There's no additional backend work needed.

**Comment by Manoj-nathwani** [comment]
huh, looks like @michaltrzesimiech decided to remove the checkbox to make users confirm they're happy giving us their information. Not sure why though, but I presume the decision was appropriately thought through.
