### ISSUE TITLE
Signup issues

### ISSUE THREAD

**Issue by sebgrebe** [rtcharity/hubreboot#134]
From @marcinkowrygo  :
a) the first word in group's name ("EA") ends up as "Ea", which looks a bit displeasing

b) what's the purpose of having two fields, one for a "regular" and one for the "LEAN" e-mail?

c) one degree of longitude/latitude equals ~111 km; while it's convenient to fill in with whole numbers, it might be a very low accuracy for most of the areas with medium of high levels of urbanization

**Comment by marcin-wosinek** [comment]
@sebgrebe do you mean feedback from me or @marcinkowrygo ?

**Comment by sebgrebe** [comment]
> @sebgrebe do you mean feedback from me or @marcinkowrygo ?

Sorry, yes! :)

**Comment by Richenda** [comment]
I'm a bit concerned to read that there is still 'email' and 'lean email' in the list of data. Pretty sure that I clarified which fields we want to keep/add a week ago. Did my list get missed? Do I need to clarify again? @Manoj-nathwani Perhaps it is counterproductive to be inviting feedback from people before all the changes that are pending have been made. Otherwise people request the same changes multiple times and I worry that my first feedback didn't get seen.

**Comment by Manoj-nathwani** [comment]
# Problem A ✅ 
- Fixed it
- I was automatically formatting the name when displaying it to make names like `manoj` show up as `Manoj`. This doesn't really make sense for group names though, so i've just removed it.

# Problem ✅ 
- ¯\\_(ツ)_/¯ The old site had it so i just copied it across 
- Sorry @Richenda for not getting around to this sooner and losing track of it. I've made a card here to track it's specific progress: https://github.com/rtcharity/hubreboot/issues/145

# Problem C ✅ 
- I think you may have looked at a bad example where they gave you a really low amount of decimal places. I've checked the database and the vast majority of lat/lon combinations we have is 6 decimal places which is very very accurate:
![image](https://user-images.githubusercontent.com/2634482/51865261-ac2b3200-233d-11e9-9451-18f2026a461d.png)
- Don't think there's anything we need to fix here then

@sebgrebe If you're happy with my responses feel free to close this github issue :)

**Comment by Manoj-nathwani** [comment]
@sebgrebe If you're happy with my responses feel free to close this github issue :)
