### ISSUE TITLE
Richenda's List of Outstanding Stuff

### ISSUE THREAD

**Issue by Richenda** [rtcharity/hubreboot#137]

**Comment by Richenda** [comment]
Here's all the stuff I can see that still hasn't been corrected (Observed 24th January) Please pardon me if you are busy doing this and I just don't know.

- [ ] Main Hub menu needs to be three horizontal lines, and a hamburger drop down (see attached image) 

- [ ] resources.eahub.org needs to be edited to match the Groups and Profiles sections. The menu must be merged with that of the complete Hub, the title and subtext needs to be removed, the rows of faces needs to be removed.

- [ ] Each of the section pages (EA Groups, Profiles, Resources) should have /feature after the EA Hub logo. For example: EA Hub / Groups, EA Hub / Profiles, EA Hub / Resources. Like Manoj included when he built the groups webapp for the first time.

- [ ] Font for the labels of the features on the Home page needs to be smaller and semi-bold (or just bold).

- [ ] Is there a reason that there are now big gaps between the edge of the header and either end of the rows of faces? It looks better if they span the width of the screen. But if that is a nightmare to handle given different devices and OSes feel free to ignore.

- [ ] The default profile images (I know you are working on this, last I saw. Just adding it to the list to be complete)

- [ ] The giant pink banner with the blue heart and GDPR needs to be redesigned. I'll do it. 

- [ ] IF we are delivering this aspect this release, then we need the option of the two other filters for sorting the list of groups (type and location, default is alphabetical).

- [ ] I'm a bit confused by the change to what the group profile page looks like design wise. There used to be a purple block for 'key facts' now it's mostly white and the other grey blocks have been whited? Is this temporary or a bug or something?

<img width="135" alt="screenshot 2019-01-25 at 01 44 29" src="https://user-images.githubusercontent.com/14843012/51738096-25c3d700-2043-11e9-9a69-812ce07463cb.png">

That's everything I can see :)

**Comment by sebgrebe** [comment]
> Main Hub menu needs to be three horizontal lines, and a hamburger drop down (see attached image)
@Richenda, We consciously decide against this as it is unusual to have a hamburger menu on a desktop page. The hamburger menu still exists on mobile. Let us know if you feel strongly about this.

**Comment by sebgrebe** [comment]
> resources.eahub.org needs to be edited to match the Groups and Profiles sections. The menu must be merged with that of the complete Hub, the title and subtext needs to be removed, the rows of faces needs to be removed.
@Richenda This is in progress, I have been working on it last week. I hope to get this done by Wednesday. I'd noticed though that the menu can't be fully merged with the hub menu, because we definitely need the resources sections as menu points (it would be inconvenient if users always had to go back to the home page to get a list of the sections). But I'll add some core hub-menu points to the menu

**Comment by sebgrebe** [comment]
> Each of the section pages (EA Groups, Profiles, Resources) should have /feature after the EA Hub logo. For example: EA Hub / Groups, EA Hub / Profiles, EA Hub / Resources. Like Manoj included when he built the groups webapp for the first time.
Created ticket, should be a quick one

**Comment by sebgrebe** [comment]
> Font for the labels of the features on the Home page needs to be smaller and semi-bold (or just bold).

@Richenda Done.

**Comment by sebgrebe** [comment]
> Is there a reason that there are now big gaps between the edge of the header and either end of the rows of faces? It looks better if they span the width of the screen. But if that is a nightmare to handle given different devices and OSes feel free to ignore.

Yes, @Manoj-nathwani added this to ensure cross-browser and -device compatibility. I think it's safer to leave it like this.

**Comment by sebgrebe** [comment]
> The default profile images (I know you are working on this, last I saw. Just adding it to the list to be complete)

@Richenda As you said, @Manoj-nathwani and @taymonbeal are working on this.

**Comment by sebgrebe** [comment]
> The giant pink banner with the blue heart and GDPR needs to be redesigned. I'll do it.

I have made a [ticket](https://github.com/rtcharity/hubreboot/issues/139).

**Comment by sebgrebe** [comment]
> IF we are delivering this aspect this release, then we need the option of the two other filters for sorting the list of groups (type and location, default is alphabetical).

You need to check with @Manoj-nathwani how likely it is to get the type distinction done before launch. My feeling is that there are more pressing issues at the moment (surrounding the profiles and their settings). Also, I might be misreading this and you might be aware of this, but we already can sort by location.

**Comment by sebgrebe** [comment]
> I'm a bit confused by the change to what the group profile page looks like design wise. There used to be a purple block for 'key facts' now it's mostly white and the other grey blocks have been whited? Is this temporary or a bug or something?

@Richenda  I've made a [ticket](https://github.com/rtcharity/hubreboot/issues/140), will do this.

**Comment by Richenda** [comment]
>We consciously decided against this as it is unusual to have a hamburger menu on a desktop page. The hamburger menu still exists on mobile. Let us know if you feel strongly about this.
@sebgrebe sorry whose we? As PM I need to be included in any decisions about design. If it's about tech architecture that's different.

So maybe I am using the description wrong here? I'll just spell out what I mean as plainly as I can to make sure :) On all versions of the Hub, no matter what device, the menu needs to be compacted into a single icon on the top right that is three horizontal lines. Clicking on that line should result in a drop down menu. Can you confirm that we're talking about the same thing?

It is interesting that this style supposed to be unusual on a desktop website. I have to say I've not noticed that. I have used many websites on my laptop that present their menus in this way too. It looks much cleaner and more minimalist. What we have now is cluttered, it takes away from the other objects on the page. Also it is redundant. The home page already has big obvious feature icons for important features. So there is no need at all to _additionally_ have a row of options in the header.

If there isn't any technical barrier then yes please, I am very certain about this design choice.

**Comment by Richenda** [comment]
> > Each of the section pages (EA Groups, Profiles, Resources) should have /feature after the EA Hub logo. For example: EA Hub / Groups, EA Hub / Profiles, EA Hub / Resources. Like Manoj included when he built the groups webapp for the first time.
> 
> @Richenda Done.

Woohoo!

**Comment by sebgrebe** [comment]
> > We consciously decided against this as it is unusual to have a hamburger menu on a desktop page. The hamburger menu still exists on mobile. Let us know if you feel strongly about this.
> > @sebgrebe sorry whose we? As PM I need to be included in any decisions about design. If it's about tech architecture that's different.
> 
> So maybe I am using the description wrong here? I'll just spell out what I mean as plainly as I can to make sure :) On all versions of the Hub, no matter what device, the menu needs to be compacted into a single icon on the top right that is three horizontal lines. Clicking on that line should result in a drop down menu. Can you confirm that we're talking about the same thing?
> 
> It is interesting that this style supposed to be unusual on a desktop website. I have to say I've not noticed that. I have used many websites on my laptop that present their menus in this way too. It looks much cleaner and more minimalist. What we have now is cluttered, it takes away from the other objects on the page. Also it is redundant. The home page already has big obvious feature icons for important features. So there is no need at all to _additionally_ have a row of options in the header. At most we can have the log in icon in addition to the menu icon.
> 
> If there isn't any technical barrier then yes please, I am very certain about this design choice.

OK, I'll fix this then! It shouldn't be too difficult.

**Comment by Manoj-nathwani** [comment]
![](https://media1.giphy.com/media/l0Ex3vQtX5VX2YtAQ/giphy.gif)
# 🏆 Sebastiankilled it once again 🏆

**Comment by Manoj-nathwani** [comment]
@sebgrebe can we close this card now?

**Comment by Richenda** [comment]
> # 🏆 Sebastian killed it once again 🏆

For he's a jolly good felloowww... 🎼
