### ISSUE TITLE
Redesign pink banner

### ISSUE THREAD

**Issue by sebgrebe** [rtcharity/hubreboot#139]
@richenda said [here](https://github.com/rtcharity/hubreboot/issues/137) : "The giant pink banner with the blue heart and GDPR needs to be redesigned. I'll do it."

@Richenda: before you start this, check first with @Manoj-nathwani and @taymonbeal whether it makes sense for you to do that. They might have plans to design the "privacy experience" in a different way than it currently is

**Comment by Richenda** [comment]
Yeh I've not forgotten. Just leaving it for last because it's a quick fix and I need to first respond to outstanding queries and things to not hold other tasks back. Think I'll be done with it tomorrow.

**Comment by Richenda** [comment]
https://drive.google.com/open?id=1vcqIjf5Vqo29sEe4YdFQUh_qOlWafIBV

**Comment by Richenda** [comment]
> @sebgrebe --> https://drive.google.com/file/d/1vcqIjf5Vqo29sEe4YdFQUh_qOlWafIBV/view

Lol.

**Comment by sebgrebe** [comment]
Thank you @Richenda. Implemented.

**Comment by Richenda** [comment]
Yesss!!! Liberation from pink!
