### ISSUE TITLE
Richenda's comments on Marcin's list

### ISSUE THREAD

**Issue by sebgrebe** [rtcharity/hubreboot#143]
[Marcin's list](https://docs.google.com/spreadsheets/d/1qotdbleP9NHHieVsFkO2LQ6qeI43wBF2P0m_2NOe-xw/edit#gid=0)

**Comment by Manoj-nathwani** [comment]
@sebgrebe This done?

**Comment by sebgrebe** [comment]
> @sebgrebe This done?

nope, next on my list (tomorrow) :)

**Comment by Manoj-nathwani** [comment]
haha sorry, there's no rush.
I was just running through all cards 🤓

**Comment by sebgrebe** [comment]
@Richenda I think this is all done now. I only saw one comment that seemed to require direct action: left aligning profile pictures and names - I've implemented this. Did I overlook anything that's pre-launch priority? If not, you can close this card and move to done.

**Comment by sebgrebe** [comment]
@Richenda Done :)

**Comment by Richenda** [comment]
> @Richenda Done :)

I LOVE IT.
@Manoj-nathwani @sebgrebe do you think we need a space between the / and 'groups' or 'profiles' or is that nitpicking? I will admit I simply do not know. Typography stuff is hard. Low priority.

**Comment by Manoj-nathwani** [comment]
@Richenda nah it's annoying enough to fix, done ✅ 

![image](https://user-images.githubusercontent.com/2634482/52046692-43130c80-253f-11e9-90b9-68361a599fec.png)
