### ISSUE TITLE
Give groups just one email field

### ISSUE THREAD

**Issue by Manoj-nathwani** [rtcharity/hubreboot#145]
# Problem
- Groups have both a `official_email` & `lean_email` field

# Solution
- Export out the data to a csv file
- Get @Richenda or someone to combine the fields and figure out which email address to keep when we have data for both fields
- On the site, combine them to just one field

**Comment by Manoj-nathwani** [comment]
Passed on a little data cleaning to Richenda here: https://rtcharity.slack.com/archives/GF1K33GAJ/p1548711106010000?thread_ts=1548708698.005500&cid=GF1K33GAJ

**Comment by Richenda** [comment]
We are done I believe. Thank you Dream Team!

**Comment by Manoj-nathwani** [comment]
Yep!
Updated the database with the changes you made in the google sheet yesterday too ✅

**Comment by Richenda** [comment]
Yay! Thank you!
