### ISSUE TITLE
Delete profile or group flows

### ISSUE THREAD

**Issue by Manoj-nathwani** [rtcharity/hubreboot#146]
# Problem
- In order to respect GDPR we need the ability for users to remove all data we have stored on them

# Solution
Add flows for deleting profiles & groups including email confirmations etc

**Comment by Manoj-nathwani** [comment]
Done here https://github.com/rtcharity/hubreboot/commit/9770f7a1ce749c0bc62de26f630a7c377e164610

**Comment by Manoj-nathwani** [comment]
@sebgrebe can you add it to the front-end please 🙏 
You can access the URL via `{% url 'delete_profile' %}`

**Comment by sebgrebe** [comment]
@Manoj-nathwani Done.

**Comment by Manoj-nathwani** [comment]
Yes i'll deff do it BEFORE launch

**Comment by Manoj-nathwani** [comment]
Thanks for sorting out the front-end :)

**Comment by taymonbeal** [comment]
Duplicate of #304
