### ISSUE TITLE
Some group profiles don't display map data

### ISSUE THREAD

**Issue by michaltrzesimiech** [rtcharity/hubreboot#147]
It looks like some group profiles don't display map data, i.e.:

https://eahub.azurewebsites.net/group/572
https://eahub.azurewebsites.net/group/518

![image](https://user-images.githubusercontent.com/14195560/51881897-c65f1300-2331-11e9-9b6c-28a78641e34f.png)

There are groups that don't have their locations filled in completely and yet display position on the map: https://eahub.azurewebsites.net/group/254

**Comment by Manoj-nathwani** [comment]
# Problem
Currently the map works off the lat/lon data we have in the database

So `/group/572` didn't give us a lat/lon
![image](https://user-images.githubusercontent.com/2634482/51902348-b424b980-23b1-11e9-9b27-00b84b3eae60.png)

and `/group/254` did:
![image](https://user-images.githubusercontent.com/2634482/51902365-bf77e500-23b1-11e9-9f5f-83780e6206ed.png)

# Solution
![image](https://user-images.githubusercontent.com/2634482/51902678-75433380-23b2-11e9-93a3-f17d969a297c.png)

- If we have no `lat/lon` for a group however we have a `town_or_city` or even `country`, set that as the marker point.
- This way even if we don't have a super accurate gps coordinate, we can still put them on the map to make the site look pretty

**Comment by sebgrebe** [comment]
@Manoj-nathwani Could you point me to the API you've been using for turning town/city/country to lat/lon?

**Comment by Manoj-nathwani** [comment]
# Update
- After talking on slack, we've decided to do exactly what we've done with the profiles and remove the lat/lon from groups and simply set it to `town_or_city` or `country`
- So this is now a backend task and not front-end as we'll always have a lat/lon providing there's other location info
- we'll also have to run through the database and do a one-off conversion job of all existing data too

**Comment by Manoj-nathwani** [comment]
# Site changed ✅ 
- See update https://github.com/rtcharity/hubreboot/commit/0b807fc369e1f163fbaa72b5e9574dbf607773a5

**Comment by Manoj-nathwani** [comment]
# Site updated ✅ 
- See update https://github.com/rtcharity/hubreboot/commit/0b807fc369e1f163fbaa72b5e9574dbf607773a5

**Comment by Manoj-nathwani** [comment]
# Existing data backlogged ✅ 
- Exported all group locations from the database
- Where we had `town_or_city` and `country` I generated a `lat/lon` for them based on the `city`
- Where we had no `town_or_city` or `country` but had `lat/lon`, I converted it to `town_or_city` and then back to `lat/lon` again. Thereby anonymising location data to just `town_or_city` level accuracy rather than people's homes.
- Cleared all data on `town_or_city, country & lat/lon` and imported processed data to make sure we're not exposing any exact location data anymore 👍
