### ISSUE TITLE
Fix String values of the "Summary" fields on group profiles

### ISSUE THREAD

**Issue by michaltrzesimiech** [rtcharity/hubreboot#148]
In some cases, summaries in local group profiles point users to wrong email addresses. We could probably fix this with a short script, or default all placeholder summaries to "N/A" https://rtcharity.slack.com/archives/GBUD95PT8/p1548732716219600

**Comment by Manoj-nathwani** [comment]
oh i see! Can't we can do this immediately after launch?
It doesn't seem important enough to stop launching unless you disagree.

**Comment by michaltrzesimiech** [comment]
This was done by importing fresh data from the airtable!
