### ISSUE TITLE
Remove "images" field from group model

### ISSUE THREAD

**Issue by Manoj-nathwani** [rtcharity/hubreboot#150]
# Problem
- The Images feature for groups in unnecessary seeing as it doesn't provide much value and only 1 group even uploaded any pictures to it in the history the old hub had the feature

# Solution
- Just remove the field from the backend & frontend

**Comment by taymonbeal** [comment]
Fixed in 7f39c1b7f92c215f505c8bf9203c7ba28e509e15.
