### ISSUE TITLE
Look into database backups

### ISSUE THREAD

**Issue by Manoj-nathwani** [rtcharity/hubreboot#153]
# Problem
- We're not sure what our backup situation is with Azure

# Solution
- Make sure we have automated backups being run as often as we need

**Comment by Manoj-nathwani** [comment]
# Current status
![image](https://user-images.githubusercontent.com/2634482/51939631-df39f800-2407-11e9-8641-cfa95cc71ee4.png)
- Looks like we have `Point-in-time restores` available through Azure which is set to 7 days

# Further questions
- Is 7 days of backups enough?
- I get the sense for a site like this having a weekly backup stored and kept for 6 months in a simple dump of our tables in blob storage may be a good idea. That way if we discover data integrity issues, we can restore back several weeks/month to when the bug was fist introduced. Does this make sense?

**Comment by Manoj-nathwani** [comment]
@michaltrzesimiech & @taymonbeal --> what do you think?

**Comment by taymonbeal** [comment]
I think Azure can provide something like that automatically without us needing to manage the blobs.
