### ISSUE TITLE
Error pages

### ISSUE THREAD

**Issue by sebgrebe** [rtcharity/hubreboot#155]

**Comment by taymonbeal** [comment]
This also needs to include 400, 403, and 500 pages.

**Comment by sebgrebe** [comment]
added [here](https://github.com/rtcharity/hubreboot/tree/155-add-404).
Cannot really test at the moment as pages don't show when Debug=True. When I set Debug=False, the page is completely messed up, so I can’t really judge it either. 

Any idea how to get around this issue? @taymonbeal @Manoj-nathwani
