### ISSUE TITLE
Add "OTHER" to "GROUP_TYPE_CHOICES" in the class Group

### ISSUE THREAD

**Issue by michaltrzesimiech** [rtcharity/hubreboot#156]
Add "OTHER" to

GROUP_TYPE_CHOICES = [
        ('COUNTRY', 'Country'),
        ('CITY', 'City'),
        ('UNIVERSITY', 'University')
    ]

**Comment by Manoj-nathwani** [comment]
Moved over to https://github.com/rtcharity/hubreboot/issues/168
