### ISSUE TITLE
Navbar disables all other elements horizontal to it when open

### ISSUE THREAD

**Issue by Manoj-nathwani** [rtcharity/hubreboot#160]
# Problem
- When the navbar is open, other elements horizontal to it on the page don't work 
- Click to open video
[![Everything Is AWESOME](https://i.imgur.com/Foyf3vo.png)](https://youtu.be/ymv3EnRa4Nw)

# Soltion
- Likely just a z-index fix: https://www.w3schools.com/cssref/pr_pos_z-index.asp

**Comment by sebgrebe** [comment]
@Manoj-nathwani Thanks for finding this. Fixed. Was indeed a z-index issue.
