### ISSUE TITLE
Potential data quality issue: names mixed up across users

### ISSUE THREAD

**Issue by taymonbeal** [rtcharity/hubreboot#167]
https://eahub.azurewebsites.net/profile/4994 is my profile and it has another user's first name. This wasn't the case on the old Hub and I didn't change it.

**Comment by Manoj-nathwani** [comment]
Yes this is definitely needs to be researched as #1 priority. I'll leave it with you for now 👍

**Comment by Manoj-nathwani** [comment]
Any updates on this @taymonbeal? It's been a week so i presume it was done a while ago?

**Comment by taymonbeal** [comment]
I wasn't able to reproduce whatever went wrong here. The only idea I have is to redo the migration from the original sources, using a fully automatic and checked-in (and ideally tested) code path. I've been trying to figure out how to make that work but it's been hard to find time this week to sit down and do a largeish project.

**Comment by taymonbeal** [comment]
(The original bug is not in the original database.)

**Comment by Manoj-nathwani** [comment]
Just fixed this by re-migrating all old usernames to the new platform again ✅

**Comment by Manoj-nathwani** [comment]
Script used:
```
# -*- coding: utf-8 -*-
import os, csv, glob, unicodedata, json
from bs4 import BeautifulSoup

def files_in_directory(directory):
  return glob.glob(directory)

def file_get_contents(filename):
  with open(filename, 'rU') as f:
    return f.read()

with open('profile_usernames.csv', 'w') as csvfile:
  spamwriter = csv.writer(csvfile)

  for file in files_in_directory('/users/manoj/eahub_cache/profiles/*'):
    html_doc = file_get_contents(file)
    soup = BeautifulSoup(html_doc, 'html.parser')

    profile_id = file.split('/')[-1].split('.')[0]
    username = soup.find('h1').text

    print(username)
    
    spamwriter.writerow([
      profile_id,
      username.encode('ascii', 'ignore'),
    ])
```
