### ISSUE TITLE
Profile page: check html (e.g., bouncy stuff)

### ISSUE THREAD

**Issue by sebgrebe** [rtcharity/hubreboot#176]

**Comment by Manoj-nathwani** [comment]
# Problem
- If effective market research isn't carried out on the bounciness of our website we may not be able to optimally provide value to our users 

| Too bouncy | Not bouncy enough |
|-------------------|------------|
| ![](https://media3.giphy.com/media/3oEduVY5mqa2GDxgcM/giphy.gif)| ![](https://media.giphy.com/media/rvhps5a80Ov4s/giphy.gif)|

# Solution
- Find happy medium of how bouncy we want the site

**Comment by sebgrebe** [comment]
I've removed the bounciness because we've so far only used it for links.
Tidied up [other stuff](https://github.com/rtcharity/hubreboot/pull/179), too

**Comment by Manoj-nathwani** [comment]
Awesome yeah that makes perfect sense 👌
