### ISSUE TITLE
Update footer

### ISSUE THREAD

**Issue by michaltrzesimiech** [rtcharity/hubreboot#177]
Let's update the footer to 

> © 2019 Effective Altruism Hub. Licensed under the MIT License. Privacy Policy. Fork here. About. Contact us.

We'll link to the license in "MIT License", link to the repo in "Fork here", the About page in "About" and add "mailto:lean@eahub.org" to "Contact us".

**Comment by Richenda** [comment]
Looks good to me.

**Comment by sebgrebe** [comment]
@michaltrzesimiech Implement. Close and move to done if happy.
