### ISSUE TITLE
EA Resources: fix links before hard launch

### ISSUE THREAD

**Issue by sebgrebe** [rtcharity/hubreboot#183]
Currently: 
- the links on EA Resources to the hub direct to https://eahub.azurewebsites.net rather than eahub.org.
- the link on the hub to EA Resources direct to https://confident-minsky-f713d6.netlify.com/, rather than resources.eahub.org

Fix this before we go live properly

**Comment by sebgrebe** [comment]
@Manoj-nathwani @taymonbeal 
Which pages are we launching with on Monday (18/2)? 
- groups.eahub.org
- staging.eahub.org
- both?

Need to know so that I can update the links from resources.eahub.org to the hub accordingly. 

Also, should I remove any links to /profile on resources.eahub.org as we're launching without profiles? Or is that not necessary?

**Comment by Manoj-nathwani** [comment]
- eahub.org should be the domain we're using for going live with the hub
- we also have groups.eahub.org which @taymonbeal sorted out as a last minute to allow another org to access our data, but they're not a priority.

**Comment by taymonbeal** [comment]
Don't link anything to groups.eahub.org, that's just going to redirect to eahub.org after the launch.

**Comment by sebgrebe** [comment]
now linking to eahub.org. This is ready to go live at the push of a button

**Comment by piotr-asdf** [comment]
I'd just like to add that currently only navmenu resources link links to https://confident-minsky-f713d6.netlify.com other links link to https://resources.eahub.org

**Comment by sebgrebe** [comment]
Updated navmenu, thanks @piotr-asdf 
(this is on master, but not deployed. Will be visible with the next deployment)

**Comment by michaltrzesimiech** [comment]
@sebgrebe should we close this by now?

**Comment by sebgrebe** [comment]
still haven't made the "new" resources live - this will be done once eahub goes live and can be done by accepting [this PR](https://github.com/rtcharity/resources.eahub.org/pull/357). Don't want to close this issue so that we don't forget about it :)

**Comment by sebgrebe** [comment]
Done: resources.eahub.org
