### ISSUE TITLE
Change image for 'Cause Area' section of personal profiles

### ISSUE THREAD

**Issue by Richenda** [rtcharity/hubreboot#192]
As above.

**Comment by Manoj-nathwani** [comment]
![image](https://user-images.githubusercontent.com/2634482/52258996-ad6ae900-2953-11e9-9dce-f4e768da3f67.png)

@Richenda this is a card for you to redesign the logo right? I'll deassign Seb for now and you can add him back once it's ready :)

**Comment by Richenda** [comment]
https://drive.google.com/open?id=1mr9pWaWLwbi3cayuCGpR8JKhbdmFSmFF
@sebgrebe
