### ISSUE TITLE
No 'save' button for /profile/edit/community /careers and /cause_areas

### ISSUE THREAD

**Issue by michaltrzesimiech** [rtcharity/hubreboot#195]
![image](https://user-images.githubusercontent.com/14195560/52248758-cd8f9f00-28a4-11e9-8098-b6c8048fa962.png)

URL: https://eahub.azurewebsites.net/profile/edit/community

**Comment by michaltrzesimiech** [comment]
Actually, "Careers" and "Cause Areas" don't have save buttons neither

**Comment by michaltrzesimiech** [comment]
And "Edit" for "Summary" leads to https://eahub.azurewebsites.net/profile/edit

**Comment by michaltrzesimiech** [comment]
![image](https://user-images.githubusercontent.com/14195560/52249495-46442a80-28a8-11e9-9105-5701ad12a4e1.png)

Similarly for deleting a profile

**Comment by sebgrebe** [comment]
My bad, guys! Sorry. Fixed.
