### ISSUE TITLE
Password reset sends two resets

### ISSUE THREAD

**Issue by michaltrzesimiech** [rtcharity/hubreboot#198]

**Comment by Manoj-nathwani** [comment]
@taymonbeal any updates on looking into this?

**Comment by taymonbeal** [comment]
Does it always coincide with #199, or is that a separate issue?

**Comment by Manoj-nathwani** [comment]
Let's assume so, this bug's too strange and only appeared once the redis bug came along too. Let's just mark it off as complete and keep our fingers crossed 🤞
