### ISSUE TITLE
Password reset died with `ConnectionError at /profile/reset/%, Error while reading from socket: (‘Connection closed by server.’,)`

### ISSUE THREAD

**Issue by michaltrzesimiech** [rtcharity/hubreboot#199]
Password reset died with `ConnectionError at /profile/reset/NTM4OQ/53l-a98d7a03102a74a512f7/
Error while reading from socket: (‘Connection closed by server.’,)`

**Comment by taymonbeal** [comment]
Please provide a stack trace the next time you see this.

**Comment by Manoj-nathwani** [comment]
![image](https://user-images.githubusercontent.com/2634482/52319195-f75ada00-29fa-11e9-838c-1dfc094e6b3a.png)

**Comment by taymonbeal** [comment]
I think this is still happening sometimes.

**Comment by Manoj-nathwani** [comment]
Hiredis should fix this. If it happens again we'll make a new issue
