### ISSUE TITLE
Reimplement map

### ISSUE THREAD

**Issue by taymonbeal** [rtcharity/hubreboot#2]

**Comment by herwix** [comment]
Regarding one of your prior comments on using Google Maps. I am not sure that this is such a great idea in the long run as I have heard it's gotten pretty expensive lately (https://cloud.google.com/maps-platform/pricing/sheet/). But I am not familiar enough with the API to know what our use case would cost, resp. how far we would get with free pricing. Another option could be: https://www.mapbox.com/pricing/ or we go with **free** and open source: https://leafletjs.com/

**Comment by taymonbeal** [comment]
Normally I'm in favor of open source solutions, but Google Maps is dramatically more polished than it's competitors, and I'm familiar enough with it's API to be pretty sure it'll be easy to integrate. I think free pricing will be okay for us at least for the MVP, and if we have to switch later at least we won't have wasted much development effort.
