### ISSUE TITLE
Integrate Bootstrap Multiselect

### ISSUE THREAD

**Issue by Manoj-nathwani** [rtcharity/hubreboot#203]
# Problem
Default multiselect UX sucks
![image](https://user-images.githubusercontent.com/2634482/52323541-f6807300-2a0f-11e9-997f-a79424883ba3.png)

# Solution
Integrate this library: http://davidstutz.de/bootstrap-multiselect
![image](https://user-images.githubusercontent.com/2634482/52323722-ab1a9480-2a10-11e9-9ca7-64fc6d186f3a.png)

**Comment by Manoj-nathwani** [comment]
So on 
`form.html`

add a
```
{% block scripts %}
<script>
</script>
{% endblock %}
```

with a script like:
```
$(document).ready(function() {
    $('#example-getting-started').multiselect();
});
```

which only applied to multiselect `<select>` elements

**Comment by sebgrebe** [comment]
@Manoj-nathwani fixed by #221. Move to done if you're happy.

**Comment by Manoj-nathwani** [comment]
# Problem
- The dropdown jumps around as the options are odd sizes
- See video: https://youtu.be/mBftmZvN1NA

# Solution
- Update config to `numberDisplayed: 1`
- See docs: http://davidstutz.de/bootstrap-multiselect/#configuration-options-numberDisplayed

**Comment by sebgrebe** [comment]
Done
