### ISSUE TITLE
Capitalise 'Hub' in 'hidden profile' blurb

### ISSUE THREAD

**Issue by Richenda** [rtcharity/hubreboot#204]
<img width="961" alt="screenshot 2019-02-05 at 22 18 14" src="https://user-images.githubusercontent.com/14843012/52323935-fd69a000-2993-11e9-97fe-245a14899ff6.png">
I think it's better to write 'the new Hub' not 'hub', or 'the new EA Hub' or 'Effective Altruism Hub'.

**Comment by Richenda** [comment]
Ooh also 'Profile hidden until user confirms that they want to make public'. This needs an 'it' between 'make' and 'public'. If we want to be totally correct we will add 'This profile is' at the start.

**Comment by sebgrebe** [comment]
Done
