### ISSUE TITLE
"Request my data" feature

### ISSUE THREAD

**Issue by Manoj-nathwani** [rtcharity/hubreboot#208]
# Problem
We don't currently have a `request my data` flow

![image](https://user-images.githubusercontent.com/2634482/52328809-824fca80-2a23-11e9-836e-0b73caf04926.png)
Link: https://bit.ly/2F2WjWH

# Solution
- Make a `download my data` button on the `/profile/123` page

**Comment by taymonbeal** [comment]
Are we planning to have any user data that's not accessible through the profile editor UI? If not, I think we can just respond to any such request by telling them to go there.

**Comment by Manoj-nathwani** [comment]
I thought it has to be a download? Otherwise yeah that would totally solve this problem 😎

**Comment by Manoj-nathwani** [comment]
# Update, yep we need a download
- https://www.i-scoop.eu/gdpr/right-to-data-portability/
- "The right to data portability 1) allows data subjects to receive personal data they provided to a controller in a structured, **commonly used and machine-readable format** and 2) to transmit those data to another controller"

**Comment by Manoj-nathwani** [comment]
Done ✅ 
- https://github.com/rtcharity/hubreboot/commit/2e7b6de80b01afada5548fc1da4847373dff88e0
