### ISSUE TITLE
Integrate resource trail on the EA Hub

### ISSUE THREAD

**Issue by herwix** [rtcharity/hubreboot#21]
We should probably integrate the resource trail on the old EA hub as part of going live.

**Comment by Manoj-nathwani** [comment]
Yup! Can I get some input from @Richenda on how this will work?

**Comment by michaltrzesimiech** [comment]
@sebgrebe I think this is done now, right?

**Comment by Richenda** [comment]
> @sebgrebe I think this is done now, right?

I think it might be ready but that he's not making it live until the last minute. But from what I'm looking at right now, this change isn't live.

**Comment by michaltrzesimiech** [comment]
Ok, marking it as fix before launch

**Comment by sebgrebe** [comment]
@michaltrzesimiech this is done, but not on the resources.eahub.org page. If I switch it on on that URL, the hub is basically open to the public as anyone going to that URL would be redirected to the hub if they click on the Home button. That is, I would only switch that URL on if we're going proper public.

**Comment by Manoj-nathwani** [comment]
I think it's time to go ahead with this :D

**Comment by sebgrebe** [comment]
Resource trail is integrated, which closes this issue.
Making that integration live is issue #183

**Comment by Richenda** [comment]
Woohoo!
