### ISSUE TITLE
Pressing Edit key information on profile management, in the Key Facts field, opens the window to edit basic information which are not displayed contents of Key Facts

### ISSUE THREAD

**Issue by piotr-asdf** [rtcharity/hubreboot#213]
Pressing Edit key information on profile management, in the Key Facts field, opens the window to edit basic information (the same as Edit button on Summary field) while the field itself displays Cause Area, Career and Community properties.

**Comment by sebgrebe** [comment]
Good point. I've moved the edit button from the key facts and under the name. Should avoid confusion
