### ISSUE TITLE
Many text fields in profile sections don't seem to have character limits

### ISSUE THREAD

**Issue by piotr-asdf** [rtcharity/hubreboot#218]
It's possible to paste a book in several profile sections, probably not a problem (but people could conceivably put their cover letters or entire CV in say summary)

**Comment by piotr-asdf** [comment]
This also applies to Groups section

**Comment by piotr-asdf** [comment]
Also, when I pasted an example book in City, Country and/or Group Name section I got "something went wrong" message instead of "too many characters" that was present yesterday (yesterday it counted amount of characters above 100 and said 100 is max) (07.02.19)

**Comment by sebgrebe** [comment]
Done, slapped some max length on inputs

**Comment by taymonbeal** [comment]
Do we *want* these to have character limits? Note that there's already a limit on how large a POST request can be, which addresses DoS concerns.
