### ISSUE TITLE
Does the privacy policy let us publish aggregated/anonymized analyses of user data?

### ISSUE THREAD

**Issue by taymonbeal** [rtcharity/hubreboot#223]
If not, we should update it, because we'll probably want to do that.

**Comment by Manoj-nathwani** [comment]
@michaltrzesimiech

**Comment by michaltrzesimiech** [comment]
@taymonbeal I don't believe it does. Are there any guidelines on wording?

**Comment by taymonbeal** [comment]
I don't really have any idea other than saying straightforwardly that we do this.

**Comment by Manoj-nathwani** [comment]
Reminder to @michaltrzesimiech to sort this out asap 🙏

**Comment by Manoj-nathwani** [comment]
@michaltrzesimiech 🚨PING 🚨 
- You should probably confirm this before sending the mass email out to everyone

**Comment by michaltrzesimiech** [comment]
On it

**Comment by Manoj-nathwani** [comment]
Any updates??

**Comment by michaltrzesimiech** [comment]
@Manoj-nathwani to "How Do We Use Your Personal Information?", we need to add:

> We may create aggregate and other anonymous data from our users’ personal information. We make personal information into anonymous data by removing information that makes the data personally identifiable to you. We may use this anonymous data and share it with third parties to operate, understand and improve our platform, to develop new services, and for other lawful purposes.

**Comment by sebgrebe** [comment]
> @Manoj-nathwani to "How Do We Use Your Personal Information?", we need to add:
> 
> > We may create aggregate and other anonymous data from our users’ personal information. We make personal information into anonymous data by removing information that makes the data personally identifiable to you. We may use this anonymous data and share it with third parties to operate, understand and improve our platform, to develop new services, and for other lawful purposes.

Done.
