### ISSUE TITLE
Link to http://www.eawork.club leads to non-SSL website

### ISSUE THREAD

**Issue by piotr-asdf** [rtcharity/hubreboot#230]
Link to http://www.eawork.club leads to non-SSL website, same with priority wiki and effective thesis
I think it's worth considering putting a warning there or addressing it otherwise

**Comment by taymonbeal** [comment]
Who maintains this? Can we take it over and put it behind HTTPS?

**Comment by sebgrebe** [comment]
@taymonbeal  Henry Stanley, I know him personally. Should I ask him about this?

**Comment by taymonbeal** [comment]
Yes, just indicate that we'd like this to be behind HTTPS and that we can help make this happen if needed.

**Comment by sebgrebe** [comment]
Talked to Henry, he said he'll do this

**Comment by sebgrebe** [comment]
Checked with Henry, this is done now: https://www.eawork.club
