### ISSUE TITLE
Minor changes to 'About' page

### ISSUE THREAD

**Issue by Richenda** [rtcharity/hubreboot#231]
1) Please replace the text with this: https://docs.google.com/document/d/1ITnG8V9zfBvMr-1I2OlzUcmSLqKe_JPS8rXg8NUFhuk/edit?usp=sharing

2)  Please add this image at the top of the page above the text. https://drive.google.com/open?id=1zbnxwy_r4Ac6qfqLwF315c7ZkJQM5UAS Buttons at the bottom stay the same

3)  Add 'About' to the drop down site menu

**Comment by Richenda** [comment]
@michaltrzesimiech since you did the fine print on privacy, where do we want that. We could display that as a collapsible thing in the About page maybe?

**Comment by Manoj-nathwani** [comment]
@michaltrzesimiech 🚨 PING 🚨 
- See above question from Richenda

**Comment by Manoj-nathwani** [comment]
# Update
- Completed task 1 ✅
- See https://github.com/rtcharity/hubreboot/commit/6ef472bcf3a42238f60f8df7d99ef93989f12d0e

**Comment by michaltrzesimiech** [comment]
@Richenda any changes here?

**Comment by Richenda** [comment]
> @Richenda any changes here?

Yes. Somebody needs to link to the Github project in the text. I don't really know what link to use, so I didn't do that. Also #2 of my instructions in the opening post was not implemented.
@Manoj-nathwani @michaltrzesimiech Thanks

**Comment by sebgrebe** [comment]
Done (not live at time of comment, will deploy later today once I've gone through all my tickets)
