### ISSUE TITLE
Standardising section size (Profiles)

### ISSUE THREAD

**Issue by Richenda** [rtcharity/hubreboot#233]
<img width="924" alt="screenshot 2019-02-12 at 15 38 03" src="https://user-images.githubusercontent.com/14843012/52675629-4661ad00-2edc-11e9-92b2-6d0e4ee5527e.png">
These need to be the same height vertically. Even if there isn't that much content in them. Perhaps there can be a 'see more' link or downward arrow icon to click to expand the boxes.

This can be left until after the launch.

**Comment by Manoj-nathwani** [comment]
@sebgrebe can you look into this please 🙏 
You should be able to set a simple `min-height: 400px` kinda setting

**Comment by sebgrebe** [comment]
Done: tiles are now always height of tallest tile.

**Comment by Richenda** [comment]
Thank you!
