### ISSUE TITLE
Feedback and glitch report form

### ISSUE THREAD

**Issue by Richenda** [rtcharity/hubreboot#234]
Sorry guys I can't find the issue or thread where this was discussed. What I remember is that we concluded that a google form would be fine for this purpose and that I should create one. I don't remember why we thought it was better than an embedded form, or what the factors were.

Anyway I made a form: https://goo.gl/forms/z5WywDNfGdYwbvDz1
Please look at it and tell me if I asked the right questions and if this is what you needed. Thank you!!!

**Comment by Manoj-nathwani** [comment]
@Richenda I don't think we need anything complex as a long form will seem intimidating UX-wise. I thought we'd simply have a `feedback` field and contact details and that's it? The main thing we needed was your help as to where we put the button on the site. What do you think?

**Comment by Richenda** [comment]
Oh right. Yeh I definitely prefer that simple approach too, but I thought everyone needed something more complex.

The button should go in the About section. In fact that's what the button already there was meant for.

**Comment by Manoj-nathwani** [comment]
1) ok, so you'll update the form to make it super simple?
2) I was thinking we should make one of these to show up on every page:

![image](https://user-images.githubusercontent.com/2634482/52685452-529d4700-2f7c-11e9-8001-f1ccf8ccecda.png)

**Comment by Richenda** [comment]
> @Richenda I don't think we need anything complex as a long form will seem intimidating UX-wise. I thought we'd simply have a `feedback` field and contact details and that's it? The main thing we needed was your help as to where we put the button on the site. What do you think?

I think it should go in the footer next to Contact Us.
Sorry I'm still unclear... do you still want a google form, or just text that you will convert into some other kind of form?

**Comment by Manoj-nathwani** [comment]
@Richenda - Feel free to simply update the existing google form you made :)
@sebgrebe - This is now a front-end task for ya 🙏

**Comment by sebgrebe** [comment]
@Richenda so all that's required is a link to your google form, yes? I can stick that on the footer.

**Comment by sebgrebe** [comment]
Done (not live at time of comment, will deploy later today once I've gone through all my tickets)

**Comment by Richenda** [comment]
> @Richenda so all that's required is a link to your google form, yes? I'll change the button on the about page accordingly.
> We should definitely integrate this form into the hub itself in the long run

Great. I'll change the form today but the link will stay the same.

**Comment by Richenda** [comment]
<img width="552" alt="screenshot 2019-02-16 at 14 34 41" src="https://user-images.githubusercontent.com/14843012/52906008-3b6a8d80-31f8-11e9-9175-bc0a2ddebe51.png">
FYI

**Comment by Richenda** [comment]
Ok the form has been simplified, Manoj
