### ISSUE TITLE
Let's make the profile/signup/ suggestions more subtle and neutral

### ISSUE THREAD

**Issue by michaltrzesimiech** [rtcharity/hubreboot#235]
![image](https://user-images.githubusercontent.com/14195560/52740730-87af9680-2f88-11e9-8466-41a731a6e02c.png)

i.e.

First Name 
Peter
Last Name 
Fiddler
Email address 
peter_fiddler@eahub.org
Password 
***
Confirm Password 
***

**Comment by taymonbeal** [comment]
I think it's very unusual to put a fake name and email address and password in the field placeholders. I can't recall another site that does this. Why are we doing it?

**Comment by sebgrebe** [comment]
went with @taymonbeal's suggestion and just removed the placeholders.
Done (not live at time of comment, will deploy later today once I've gone through all my tickets)
