### ISSUE TITLE
Change speaking suggestions to "I.e. AI technical safety, global health"

### ISSUE THREAD

**Issue by michaltrzesimiech** [rtcharity/hubreboot#238]
![image](https://user-images.githubusercontent.com/14195560/52742264-3e614600-2f8c-11e9-881f-89075ec37047.png)

**Comment by michaltrzesimiech** [comment]
Also appears in /profile/edit/career
![image](https://user-images.githubusercontent.com/14195560/52742449-99933880-2f8c-11e9-9226-766560922757.png)

**Comment by Manoj-nathwani** [comment]
Done ✅ 
https://github.com/rtcharity/hubreboot/commit/da4295007d25f24c5e99fb03b21ca1be7bc038e8
