### ISSUE TITLE
Key facts don't display "Cause areas" when filled 

### ISSUE THREAD

**Issue by michaltrzesimiech** [rtcharity/hubreboot#239]
![image](https://user-images.githubusercontent.com/14195560/52742572-de1ed400-2f8c-11e9-9efd-b82650f55078.png)

I.e. https://staging.eahub.org/profile/14037

**Comment by Manoj-nathwani** [comment]
Works for my user https://eahub.azurewebsites.net/profile/13013
![image](https://user-images.githubusercontent.com/2634482/52761652-c7d54e80-3046-11e9-9253-2642974a4f06.png)

Only spent 10 seconds looking into this though. We'll make this a post-launch ticket 👍

**Comment by sebgrebe** [comment]
could replicate this, fixed now.
(not visible at time of comment, will deploy later)
