### ISSUE TITLE
Profile email addresses are not case sensitive thereby allowing multiple accounts to be made for the same email

### ISSUE THREAD

**Issue by Manoj-nathwani** [rtcharity/hubreboot#241]
# Problem
- The old tech used `username` as the  uniquely identifying thing for logging in. The new tech uses `email` which means that there are users who have multiple accounts linked to the same email address
- This would cause all kinds of issues as you can only log into one of those accounts
- It's worth noting that the validation on the database is set to unique email addresses however the rule didn't seem to apply to existing data.

# Solution
- Run a quick script to delete accounts where there are more than 1 `Profile` linked to a single email address. Presumably we'd keep the one with the higher `id` as it's newer.

**Comment by taymonbeal** [comment]
Wait, that can't possibly be right. Postgres enforces uniqueness constraints all the time, not just when new data is added. We'd be getting IntegrityErrors if there were really duplicates on a unique column.

Any chance this has to do with case sensitivity?

**Comment by Manoj-nathwani** [comment]
Oh looks like you're right. See this: https://rtcharity.slack.com/archives/GBUD95PT8/p1550006120035100

**Comment by taymonbeal** [comment]
I think we want to change the database column to [this](https://docs.djangoproject.com/en/2.1/ref/contrib/postgres/fields/#django.contrib.postgres.fields.CIEmailField).

**Comment by Manoj-nathwani** [comment]
Go for it 💪
