### ISSUE TITLE
Fix grammar in profile settings

### ISSUE THREAD

**Issue by Richenda** [rtcharity/hubreboot#243]
<img width="449" alt="screenshot 2019-02-14 at 10 42 30" src="https://user-images.githubusercontent.com/14843012/52811311-a164e280-3049-11e9-906c-7baa8ca0b1af.png">
"Topics I speak about" has a lower case 'i', which must be capitalised.

**Comment by Manoj-nathwani** [comment]
Fixed ✅ 
- https://github.com/rtcharity/hubreboot/commit/eac61ec13fb94e84f7c3b7b38a07954657970b31
