### ISSUE TITLE
Wrap links in EA Group 'Key Facts'

### ISSUE THREAD

**Issue by Richenda** [rtcharity/hubreboot#244]
<img width="959" alt="screenshot 2019-02-14 at 10 56 33" src="https://user-images.githubusercontent.com/14843012/52811394-d1ac8100-3049-11e9-8557-3d670dc28413.png">
The link spills out of the box perimeter.

**Comment by sebgrebe** [comment]
Done
(not visible yet as not deployed at time of comment)

**Comment by Richenda** [comment]
Thanks!
