### ISSUE TITLE
Delete weird (spam?) groups from records

### ISSUE THREAD

**Issue by Richenda** [rtcharity/hubreboot#245]
<img width="934" alt="screenshot 2019-02-14 at 10 55 59" src="https://user-images.githubusercontent.com/14843012/52811467-09b3c400-304a-11e9-9a2e-11406b599fdc.png">
When sorted by location, the last groups listed all look like this. Can we just outright delete them?

**Comment by Manoj-nathwani** [comment]
![](https://media0.giphy.com/media/oYtVHSxngR3lC/giphy.gif)

**Comment by Manoj-nathwani** [comment]
Just deleted out those crazy accounts ✅
