### ISSUE TITLE
Remove capitalisation on web address - Login form

### ISSUE THREAD

**Issue by Richenda** [rtcharity/hubreboot#246]
<img width="437" alt="screenshot 2019-02-14 at 10 34 14" src="https://user-images.githubusercontent.com/14843012/52811571-4a134200-304a-11e9-8977-cac1b0f41618.png">
EaHub.org should be changed to eahub.org here, I believe.

**Comment by Manoj-nathwani** [comment]
@michaltrzesimiech please confirm

**Comment by Manoj-nathwani** [comment]
Fixed ✅ 
- https://github.com/rtcharity/hubreboot/commit/eac61ec13fb94e84f7c3b7b38a07954657970b31
