### ISSUE TITLE
Images showing black

### ISSUE THREAD

**Issue by Richenda** [rtcharity/hubreboot#247]
<img width="686" alt="screenshot 2019-02-14 at 10 50 30" src="https://user-images.githubusercontent.com/14843012/52811654-78911d00-304a-11e9-9c1b-fdfad2d3a404.png">
This is a new profile picture I uploaded. It was a png file with a translucent square layer behind the disk. Yet it appeared black on upload. Is this something that we can alter or is it entirely to do with the file that gets uploaded?

Low priority

**Comment by Manoj-nathwani** [comment]
cc @taymonbeal 🙏

**Comment by taymonbeal** [comment]
@Richenda, can you link me to the profile that's doing this so I can see it?

**Comment by Richenda** [comment]
> @Richenda, can you link me to the profile that's doing this so I can see it?

I can't because that was my profile and now the features of the Hub are hidden I can't log into my account and upload the file that produced that effect. This was it.
![avatar61 1](https://user-images.githubusercontent.com/14843012/52888619-4e665a80-3131-11e9-8c23-91bbb7a6347a.png)

**Comment by taymonbeal** [comment]
@Richenda, you should be able to log in now.

**Comment by taymonbeal** [comment]
Managed to repro this locally. Investigating.

**Comment by taymonbeal** [comment]
Okay, the issue is that the uploaded image was a PNG, but the thumbnail is a JPEG, and JPEGs don't support transparency. Do we particularly care about supporting the use case where the user's profile picture isn't a photograph? Photographs should generally be JPEGs.

**Comment by Manoj-nathwani** [comment]
Let's just add some validation for now to make sure users can only upload JPEGs. I think there's a html way of enforcing it.
