### ISSUE TITLE
Wording change for pledges

### ISSUE THREAD

**Issue by Richenda** [rtcharity/hubreboot#248]
Should be pledge 'taken' or 'made' not 'given'.
<img width="300" alt="screenshot 2019-02-14 at 12 10 57" src="https://user-images.githubusercontent.com/14843012/52814726-a88fee80-3051-11e9-84ab-bcf7a73a7f7b.png">

**Comment by sebgrebe** [comment]
Good shout.
Done (not live at time of comment, will deploy later today once I've gone through all my comments)

**Comment by Richenda** [comment]
Thank you!
