### ISSUE TITLE
Finalise migrated Profile data

### ISSUE THREAD

**Issue by Manoj-nathwani** [rtcharity/hubreboot#250]
# Problem
- The old hub had bad data for some reason. Some users have said that their name is wrong which is a known issue, so there's clearly issues with people's names on the platform.
- This means we have no idea how much to trust any of the `Profile` data as their location data etc could be wrong too

# Solution
- Research if we want to clear out all data we have on profiles. We defiantly want to keep as a minimum their email addresses however we need to remove their name and research if their location data and groups they're organisers of can be trusted

**Comment by Manoj-nathwani** [comment]
*Potential solution*
- We delete all profiles
- We create an account for every email address we had in the old hub with zero other data filled in
- The map (for now) is populated with the old data and once we have enough users in a couple weeks, we'll switch it over to being live with existing data. This means the map will simply show dummy data which is potentially wrong however as it's anonymised anywhere, nothing is really lost by doing this.

**Comment by taymonbeal** [comment]
Have there been any known instances of this problem that were traced back to bad data in the original Hub database?

**Comment by Manoj-nathwani** [comment]
- Names have just been scraped off the old hub yet are still being reported as wrong
- Richenda has always mentioned about data issues with names though, so it's a known issue

- So we've confirmed names are wrong, we need to figure out what else is 🙈

**Comment by Richenda** [comment]
> Have there been any known instances of this problem that were traced back to bad data in the original Hub database?

When the old Hub was still running and in use, I experienced issues such as trying to edit the profile of a user at their request and then finding that it took me to somebody else's profile instead... with no clear way to find the right person's. Also more than once when users were sharing links to their accounts for me to look at, the link took me somewhere else instead and none of us could figure out how or why.

**Comment by Manoj-nathwani** [comment]
# Stakeholders have decided ✅ 

![image](https://user-images.githubusercontent.com/2634482/52841440-f3cbff00-312e-11e9-8a72-2284af7d2106.png)

![image](https://user-images.githubusercontent.com/2634482/52841480-0a725600-312f-11e9-9a3d-43b75afb5324.png)

![image](https://user-images.githubusercontent.com/2634482/52841374-bb2c2580-312e-11e9-887e-78424f2efd9f.png)

**Comment by Manoj-nathwani** [comment]
Cached map data so the profiles map is still nice and full ✅ 
- See: https://github.com/rtcharity/hubreboot/commit/866636bd79ca2e752c192559472e2950af67bbcf

Removed all `first_name & last_name` data ✅ 
```
UPDATE profiles_profile SET first_name='Hidden', last_name='User'
```
