### ISSUE TITLE
Where'd the login/signup buttons go?

### ISSUE THREAD

**Issue by Manoj-nathwani** [rtcharity/hubreboot#258]
# Problem
- If you're not logged in, there's no login/signup buttons anymore

![image](https://user-images.githubusercontent.com/2634482/52896644-63102480-31fd-11e9-8d84-ca6def32c3c2.png)

# Solution
- Add the login/signup buttons back to being tabs to the left of the hamburger menu

**Comment by sebgrebe** [comment]
someone added {%comment%} tags around the buttons, this removed the login buttons. Don't why this was done. Please let me know what the rationale was if you think they need to stay for some reason. I've removed the tag.

**Comment by sebgrebe** [comment]
done (not live at time of comment, will deploy later today once I've gone through all my comments)

**Comment by taymonbeal** [comment]
This was done because we needed to deploy the groups.eahub.org site on short notice yesterday, we didn't want the account-management stuff to be available on it, and there wasn't time to set up a separate instance of the site. Please do _not_ push this change to production without first figuring out some other solution to that problem.

**Comment by sebgrebe** [comment]
@taymonbeal this is in master now, but haven't deployed yet. Getting on a plane now and can't sort this out now.

**Comment by taymonbeal** [comment]
I think I should probably revert this commit, then, until we figure out a plan, in case someone deploys.

**Comment by Manoj-nathwani** [comment]
# Update needed
- Instead of simply having a `{% comment %}` tag, replace it with some logic to see if the current domain is `staging.eahub.org`. If it is, then hide it otherwise display the login/signup buttons

**Comment by sebgrebe** [comment]
> * Instead of simply having a `{% comment %}` tag, replace it with some logic to see if the current domain is `staging.eahub.org`. If it is, then hide it otherwise display the login/signup buttons

Added such logic. Buttons show on eahub.azurewebsites.net, but not on staging.eahub.org.

**Comment by taymonbeal** [comment]
Buttons were visible on groups.eahub.org. Commented them out again until this logic can be fixed.

**Comment by taymonbeal** [comment]
Commit is 09421a11d34e8595675279820a49117a0097adcb (forgot to link this issue in commit message).

**Comment by sebgrebe** [comment]
@taymonbeal could you clarify which buttons should not be visible on which page? I assumed login buttons shouldn't be visible on staging, but apparently there is more.

**Comment by taymonbeal** [comment]
No, staging is where we _want_ the buttons. Where we _don't_ want them is on groups.eahub.org.

**Comment by taymonbeal** [comment]
(I don't think anyone's even using eahub.azurewebsites.net anymore so it doesn't particularly matter what is or isn't visible there.)

**Comment by sebgrebe** [comment]
and which buttons? I noticed that you commented out the profiles button

**Comment by taymonbeal** [comment]
We don't want groups.eahub.org to include any links to the Profiles feature or to anything that involves users logging in or entering data. From the user's perspective it should just be a static site listing group information.

**Comment by sebgrebe** [comment]
how is this gonna work with the profiles on the map? I saw @Manoj-nathwani wrote something about dummy data on the map. Who is implementing this?

**Comment by taymonbeal** [comment]
Which map? The map on the groups page is a map of groups, not individuals, right? That should be using real data.

**Comment by sebgrebe** [comment]
> Which map? The map on the groups page is a map of groups, not individuals, right? That should be using real data.

sorry, thought groups.eahub.org would feature the home page, my bad.

**Comment by sebgrebe** [comment]
This should be what you wanted:
https://github.com/rtcharity/hubreboot/commit/2f9b6a847af2fd7e49a0be3e3f58b3092b49cd7f
Can I deploy this?

**Comment by taymonbeal** [comment]
Sure, just be sure to check the groups site and make sure it works the way we expect.

**Comment by taymonbeal** [comment]
This appears to be fixed now.
