### ISSUE TITLE
Wrong lat/lon where location empty

### ISSUE THREAD

**Issue by sebgrebe** [rtcharity/hubreboot#260]
If I remove my location on the profile/edit, my profile is given the following coordinates: lat: 44.937967, lon: 7.54004. (somewhere in Italy)

The values should be empty instead. I assume this has something to do with the plugin that changes location names to lat/lon

**Comment by Manoj-nathwani** [comment]
Done ✅ 
- Thanks for finding this!
- https://github.com/rtcharity/hubreboot/commit/181770505d924f7f8bcc8bca08b0dd8224b08c9a
