### ISSUE TITLE
Space needed after hyphen

### ISSUE THREAD

**Issue by Richenda** [rtcharity/hubreboot#261]
<img width="484" alt="screenshot 2019-02-16 at 15 55 32" src="https://user-images.githubusercontent.com/14843012/52906564-5abae800-3203-11e9-915e-38613a596c6c.png">
This is on the EA Resources page. Obviously I don't know what the status is for changes that haven't gone live yet, so sorry if this got fixed.

**Comment by sebgrebe** [comment]
Done
