### ISSUE TITLE
Allow users to subscribe to email updates on the Hub

### ISSUE THREAD

**Issue by taymonbeal** [rtcharity/hubreboot#262]
We'll be adding more features, and occasionally want to email people about them, especially for the purpose of adding more data. But we need user consent for this, and I think they'll expect to be able to control it through their account rather than a separate Mailchimp thing.

(Actually figuring out how to send such updates can wait until later, but I think the ability to opt in needs to be available immediately on account creation, or else nobody will have done this and we won't be in a good place.)

**Comment by Manoj-nathwani** [comment]
Good point 👍 

# Solution
- Take the `available_to_volunteer` field as an example and make a similar field which is a boolean with a checkbox on the `profile/edit` page where users can sign up to our newsletter
- In the short-term we can use that to make sure people who opt-out are not sent further emails
- In the long-run we'll automate emails through SendGrid and our django app for newsletters

**Comment by taymonbeal** [comment]
Can we get this onto the registration form? I suspect this matters a lot for response rates.

**Comment by Manoj-nathwani** [comment]
Yeah that should be possible. It'll be a custom field just as the captcha is.

**Comment by taymonbeal** [comment]
Fixed by #280.
