### ISSUE TITLE
Note that users who say they're looking for opportunities may be searchable

### ISSUE THREAD

**Issue by taymonbeal** [rtcharity/hubreboot#270]
This was asked for in the earlier document about model fields but then got dropped.

**Comment by sebgrebe** [comment]
This should be covered by #271 now

**Comment by taymonbeal** [comment]
This is a bit of a separate issue from that. Specifically in the places where users can specify that they're looking for opportunities, we want to say something like, "If you select this option, people will be able to search for your profile based on your listed location, skills, and cause areas." Which is distinct from having it merely be public if you already know where to find the profile.

**Comment by sebgrebe** [comment]
I assumed the search would be possible merely because the site is public and hence somewhat could find it through google search? We're not currently providing any search functionality (except for the tables on /profiles and /groups), are we?

**Comment by taymonbeal** [comment]
The plan is to add such functionality post-launch, and we don't want any users to be unpleasantly surprised when we do. See comments [here](https://docs.google.com/document/d/1eEQ6mFFX8kWb0Zbznn61HFVwr4rE3AkOaDZ_AtqRrhY/edit).

**Comment by sebgrebe** [comment]
I would just stick with what we have at the moment. 
- Users know that information is public, don't see that the fact that it shows up in some search functionality is particularly relevant
- Writing something like "Also, we plan on implementing some search in the future where your info shows up" just sounds clunky.
- Furthermore, this might be confusing for users - where will this search be, how will it work? Might create more answers than questions

**Comment by taymonbeal** [comment]
The relevant distinction here is between "users who find your profile can see this information" and "users who enter this query can use it to find your profile even if they don't otherwise know about it".

So our options are:
- Project leadership decides that we don't want to distinguish between these.
- We rule out the possibility of later letting people search on existing fields (though not necessarily on new ones that we might add later).
- We add the privacy warning.

**Comment by sebgrebe** [comment]
pinged @michaltrzesimiech about this on slack

**Comment by michaltrzesimiech** [comment]
I agree that we should make things clear, but that's once we have the search  (https://github.com/rtcharity/hubreboot/issues/28). Let's keep this issue open. I'll just change the priority of it.

**Comment by taymonbeal** [comment]
So if users enter data right after launch, without the privacy warning having been present, are we okay with it later being possible to search for them based on that data?

**Comment by michaltrzesimiech** [comment]
Ok, let's add that warning straight away @taymonbeal (CC: @Richenda)

**Comment by Richenda** [comment]
If our privacy/GDPR statement is up to scratch then nothing further is needed anywhere else.

**Comment by sebgrebe** [comment]
@Richenda and @michaltrzesimiech you seem to be contradicting each other :)

Options:
1) We extend the note under the Update button on profile/edit/career such that it fully reads as follows:
 > Note: All profile information is public. Furthermore, in the future we will implement functionality that allows users to see a list of all users open to job offers, which you will appear in if you indicate here that you are open to job offers. Read more about our privacy policy
2) We add a similar phrase in the privacy policy in the "How Do We Use Your Personal Information" section. We currently don't have anything about the search functionality there.
3) We leave everything as it is.

Personally, I'm in favour of 3) since users are made aware that their profile information is public. I don't see that the way it is made public - by someone going to their profile and seeing it there or by it showing up in a search - would be relevant.

But happy to implement whatever you prefer, just need to what you've agreed on :)

**Comment by taymonbeal** [comment]
To be clear, I do not see this as primarily about regulatory compliance, I see it as primarily about giving users accurate expectations about who their data might be shown to and under what circumstances.

**Comment by michaltrzesimiech** [comment]
My concern is that if Taymon raises this as a concern, we should expect that it can also concern a larger number of users (we should measure this at a later stage to be sure). It is also true that websites like LinkedIn warn their users about making that particular piece of information available publicly.
Our approach is to err on the side of being too careful, so let's add 

> All profile information, including your openness to receiving job offers, is public. Read more about our approach to privacy in our <Privacy Policy>.

**Comment by michaltrzesimiech** [comment]
Related: https://github.com/rtcharity/hubreboot/issues/279

**Comment by sebgrebe** [comment]
OK, I've changed the privacy note under the update button on profile/edit/career (where users enter job availability) in line with @michaltrzesimiech 's suggestion. (not deployed yet)

**Comment by Richenda** [comment]
Ok, I defer to Michal on anything related to privacy because he's the one that takes the backlash if people aren't happy.

**Comment by taymonbeal** [comment]
Good enough for now. I'd prefer something that explicitly mentions the searchability thing (partly just to avoid confusing people), but I understand wanting to wait until that feature actually exists. This'll roll out with the current deployment.
