### ISSUE TITLE
Note explicitly somewhere that all profile information is public on the internet

### ISSUE THREAD

**Issue by taymonbeal** [rtcharity/hubreboot#271]
I think at one point we were intending to implement something in the way of privacy controls, but those aren't going to exist at launch; right now, if it's on the site, it's public. So this should probably be stated explicitly at the point where information is entered. Unless people think it's already sufficiently obvious from the UI?

**Comment by sebgrebe** [comment]
![screen shot 2019-02-18 at 13 39 53](https://user-images.githubusercontent.com/15908208/52948705-c7a8bc00-3382-11e9-9d1d-e50451e8faed.png)

Added this note under the sign up button

**Comment by sebgrebe** [comment]
![screen shot 2019-02-18 at 13 40 22](https://user-images.githubusercontent.com/15908208/52948738-e60eb780-3382-11e9-9667-314780724416.png)

Added this note under the sign up button.

**Comment by sebgrebe** [comment]
@taymonbeal close if you're happy with this

**Comment by taymonbeal** [comment]
Looks good to me, at least given the current state of the tech.
