### ISSUE TITLE
Cookies Popup change

### ISSUE THREAD

**Issue by Richenda** [rtcharity/hubreboot#273]
<img width="1395" alt="screenshot 2019-02-18 at 13 05 52" src="https://user-images.githubusercontent.com/14843012/52976340-012af880-337e-11e9-9cf3-3c2925a9147d.png">
Please change the colour of the bar to HEX code #635274
The button should be HEX code #A7DBAB
The text in the button should be white.

Please reassign if appropriate. Not sure whose manning what in the last hours...
Thank you!

**Comment by sebgrebe** [comment]
Done

**Comment by Richenda** [comment]
<img width="1405" alt="screenshot 2019-02-20 at 13 09 33" src="https://user-images.githubusercontent.com/14843012/53125337-a4147b80-3512-11e9-8f37-ccb32ed4459b.png">
Almost, but not quite! The button on the right still needs white text. Sorry for the bother!
