### ISSUE TITLE
Change error message colours (Login and Signup)

### ISSUE THREAD

**Issue by Richenda** [rtcharity/hubreboot#274]
<img width="467" alt="screenshot 2019-02-18 at 13 12 25" src="https://user-images.githubusercontent.com/14843012/52976585-eefd8a00-337e-11e9-9b69-91ee62ec4407.png">
Is it possible to make the blue and red alerts show up in Hub colours instead? 
Here is the spec sheet for the colours https://docs.google.com/spreadsheets/d/1g77mKcqGFGNdpY7MFN7TA2rcVE_YIR6ob_sohb_o-0U/edit#gid=0 Hopefully lowering opacity on these colours would produce the same effect?

**Comment by sebgrebe** [comment]
Done
