### ISSUE TITLE
Sign up not working

### ISSUE THREAD

**Issue by sebgrebe** [rtcharity/hubreboot#276]
Sign up isn’t working (just tried to create a new profile), neither on staging.eahub.org nor when running the app locally.
In particular, I’m getting a 500:

``` 
duplicate key value violates unique constraint "profiles_profile_username_key"
DETAIL:  Key (username)=() already exists.
```

- I've checked both with email addresses that were linked to my old profile (but which should have been deleted when the database was deleted) and with email addresses I haven't used before. 
- I've also used another First and Last Name, in case the issue is somehow linked to my old profile.
- To check whether my old profile is still saved in some way, I tried to log into it. Returns that username and password don't match.

**Comment by taymonbeal** [comment]
Fixed by #280.
