### ISSUE TITLE
Make clear old profiles are gone

### ISSUE THREAD

**Issue by sebgrebe** [rtcharity/hubreboot#311]
**Problem:** 
Friend of mine tried to reactivate old profile by asking for password reset. 

**Solution**
On login page, make clear that old profiles have been gone

**Comment by michaltrzesimiech** [comment]
Yep, that seems like an issue that is being raised with us once in a while.

**Comment by taymonbeal** [comment]
Do we want to make any effort to bring them back?

**Comment by sebgrebe** [comment]
added explanatory note on login
