### ISSUE TITLE
Add fancy auto-hyperlinking to front end

### ISSUE THREAD

**Issue by Manoj-nathwani** [rtcharity/hubreboot#34]
The site has a lot of natural text where users have inserted links and email addresses. It would be super great to automatically detect & convert URLs into proper `<a>` tags and the same for email addresses.

I've found this library which does what we want: https://soapbox.github.io/linkifyjs/docs. We also only need to apply them to elements with the class `.text-block-from-database`

**Comment by sebgrebe** [comment]
https://github.com/rtcharity/hubreboot/pull/37

**Comment by Manoj-nathwani** [comment]
Closing as this card is in the "Done" column on the project board
If any further work is needed, make a new card :)
