### ISSUE TITLE
Profiles Wireframes

### ISSUE THREAD

**Issue by Richenda** [rtcharity/hubreboot#35]
I stayed up late finishing these so can't say a huge amount, but basically it takes you from the home page through to a profile once you click on it. The intermediary section for profiles I've covered with two different examples. Input welcome on which is best.
![home_page_december](https://user-images.githubusercontent.com/14843012/50220451-3350b780-0347-11e9-84bc-3efb9481d15b.png)
![profile_page_december](https://user-images.githubusercontent.com/14843012/50220452-3350b780-0347-11e9-971c-a4b94e7d736b.png)
![profile_section_december_ii](https://user-images.githubusercontent.com/14843012/50220454-3350b780-0347-11e9-89d0-9a2f12cc0a75.png)
![profile_section_december](https://user-images.githubusercontent.com/14843012/50220455-33e94e00-0347-11e9-9287-302afb8cbc5a.png)

**Comment by Manoj-nathwani** [comment]
THIS IS AWESOME! Maybe it's worth splitting each page into it's own github issue. I want to ask in-depth questions such as "what's the columns in the last image?", but on each wireframe, so I think it'll be easier to keep track of conversations regarding each wireframe if each one is it's own github issue.

**Comment by Richenda** [comment]
Thanks very much for actioning Manoj's suggestion @sebgrebe 
Yeh I think it's fine that some things might only be added at later points in time.
