### ISSUE TITLE
Wireframes: Home page

### ISSUE THREAD

**Issue by sebgrebe** [rtcharity/hubreboot#38]

**Comment by sebgrebe** [comment]
![wireframe_home](https://user-images.githubusercontent.com/15908208/50273461-adaa3600-0432-11e9-8aab-bde1970bc3d9.png)

**Comment by sebgrebe** [comment]
One issue I had on the resources page was that the burger menu when unfolded overlaps the faces. Due to this, I ended up with having a big gap between the burger menu and the faces to avoid that,  which looks a bit awkward. 

Would it be OK if the drop down menu overlaps the faces? @Richenda

**Comment by sebgrebe** [comment]
What's the caption? @Richenda

**Comment by sebgrebe** [comment]
Do we already have the feature icons or do they have to be made first?

**Comment by Richenda** [comment]
> I need links to
> 
> * EA projects ([this](https://forum.effectivealtruism.org/posts/LG6gwxhrw48Dvteej/concrete-project-lists)?)
> * Priorities Wiki ([this](http://priority.wiki/)?)
> * Community & Discussion ([EA Forum](https://forum.effectivealtruism.org/)?)
> * Survey: ([this](https://forum.effectivealtruism.org/posts/S2Sonawxz2cY4YdXK/ea-survey-2018-series-community-demographics-and)?). Surprised to see that the survey doesn't have his own webpage.
> 
> Or will we have to build any of these webpages (an own place for the survey in particular seems to make sense to me)?

Some of these, such as projects and the survey dashboard) are things that don't exist yet but will on the final end state Hub, according to my current view. I will update as we go. The priority wiki link is correct. And the forum link. But I am making wireframes for those things bit by bit.

**Comment by Richenda** [comment]
> The list of icons imply that profiles, groups and maps are different pages. Atm, we display the maps on the profiles and groups pages, i.e., there is no individual maps page. Shall we change this?

Yes I think there should be a designated map page. A lot of people used the Hub specifically for the map.

**Comment by Richenda** [comment]
> Do we already have the feature icons or do they have to be made first?
> Made a [ticket](https://github.com/rtcharity/hubreboot/issues/45) for this

We have all feature icons.

**Comment by Richenda** [comment]
> One issue I had on the resources page was that the burger menu when unfolded overlaps the faces. Due to this, I ended up with having a big gap between the burger menu and the faces to avoid that, which looks a bit awkward.
> 
> Would it be OK if the drop down menu overlaps the faces? @Richenda

Oh yes totally fine with an overlap, though this means that the menu should not be translucent but solid in colour. Perhaps pale grey.

**Comment by sebgrebe** [comment]
@Richenda I've basically designed the home page now, can show you once it's gone through Manoj's review. What I didn't implement though were the "hover texts for feature links". Could you provide me with some content for those?
