### ISSUE TITLE
Wireframes: Profile

### ISSUE THREAD

**Issue by sebgrebe** [rtcharity/hubreboot#39]

**Comment by sebgrebe** [comment]
![wireframe_profile](https://user-images.githubusercontent.com/15908208/50273537-da5e4d80-0432-11e9-8c27-bc977bc882b6.png)

**Comment by Richenda** [comment]
Thank you
> I could imagine that setting up our own messaging system is quite labour-intensive and I don't think it adds lots of benefits as there's already so many other means of communication out there. Maybe a simple @MAILTO or link to fb would do? At least before the release

Yeh that is really all I meant. The old Hub had something like this. So I am just talking in terms of replacing that. The main thing is that it should not be possible for the sender to see the email address. I know for a fact that people made use of it, so I think it's worth putting back.

**Comment by Richenda** [comment]
Regarding the Key Facts box: to elaborate on my caption...
Is it possible that the box will only display a row of information IF the user fills it in? For example, we give them the option to put down what their donations are, but if they don't report any donations, can the row for donations not be visible in the Key Facts area?

**Comment by sebgrebe** [comment]
> Regarding the Key Facts box: to elaborate on my caption...
> Is it possible that the box will only display a row of information IF the user fills it in? For example, we give them the option to put down what their donations are, but if they don't report any donations, can the row for donations not be visible in the Key Facts area?

No problem at all.

**Comment by Manoj-nathwani** [comment]
@Richenda Can you confirm each of the "key facts" we want to ask users to fill in?

**Comment by Richenda** [comment]
> @Richenda Can you confirm each of the "key facts" we want to ask users to fill in?

In the image is:
Cause Areas
Donations (Total) 
Direct Work Hours (Total) 
Expertise (Academic or Professional)
Speaker (Yes/No)
Group
Skills
Volunteer (Yes No)
Job Status (Employed, Unemployed, Seeking Work, Seeking Voluntary Work, Open to Offers)
EA Organisation Affiliation (For people who work or volunteer for EA orgs. They can select more than one)

If you have a list of data that we have for profiles already I can comment on if any need to be merged, removed, and if any others should be added to the database. Most of these new ones requested by me we will have to rely on users filling in once the site is live.

**Comment by sebgrebe** [comment]
@Manoj-nathwani 
For the fields on @Richenda's [list](https://github.com/rtcharity/hubreboot/issues/39#issuecomment-452541609) that aren't in the database yet: 
1) Should I add fields for them in the homepage using plausible names (e.g., {{ profile.expertise }} ) and you can then check them and build them into the database? OR
2) Do you want to build them first. You can then leave a comment here that it's done, and I'll implement the new fields on the frontend

**Comment by Manoj-nathwani** [comment]
![image](https://user-images.githubusercontent.com/2634482/51084735-e8984480-1726-11e9-8f9c-24e602d00e49.png)

**Comment by Manoj-nathwani** [comment]
# All done ✅ 
- Code: https://github.com/rtcharity/hubreboot/commit/0cfaf9b59c356cd61e079416fcb210c35b71b431
- Wired up all new fields to the backend
- Removed `info` as it was redundant
- Removed `direct_work_hours` as I wasn't sure what it meant and we can figure out what it should mean in the future
