### ISSUE TITLE
Make individual page for map

### ISSUE THREAD

**Issue by sebgrebe** [rtcharity/hubreboot#50]
This ticket became necessary because of this:
> The list of icons imply that profiles, groups and maps are different pages. Atm, we display the maps on the profiles and groups pages, i.e., there is no individual maps page. Shall we change this?

Yes I think there should be a designated map page. A lot of people used the Hub specifically for the map.

_Originally posted by @Richenda in https://github.com/rtcharity/hubreboot/issues/38#issuecomment-449181295_

**Comment by michaltrzesimiech** [comment]
@sebgrebe do we still need this?

**Comment by sebgrebe** [comment]
@michaltrzesimiech no
