### ISSUE TITLE
Provide content for "hover texts for feature links"

### ISSUE THREAD

**Issue by sebgrebe** [rtcharity/hubreboot#51]
@Richenda I've basically designed the home page now, can show you once it's gone through Manoj's review. What I didn't implement though were the "hover texts for feature links". Could you provide me with some content for those?

_Originally posted by @sebgrebe in https://github.com/rtcharity/hubreboot/issue_comments#issuecomment-449188512_

**Comment by Richenda** [comment]
Provided here https://github.com/rtcharity/hubreboot/issues/45
