### ISSUE TITLE
Feedback: Profile page

### ISSUE THREAD

**Issue by sebgrebe** [rtcharity/hubreboot#54]
First version of the profile page: https://eahub.azurewebsites.net/profile/5389

Currently with dummy data, default picture, and mute connect button.

Feel free to leave feedback in the comments, I'll try to implement it.

**Comment by Richenda** [comment]
Great start!
Some changes to make it better...
1) Profile avatar should be to the left of the user name
2) The grey boxes should be much more pale grey. The grey is there to help your eyes find the right block of text and to separate it from the environment. But without registering it as being a big colour difference.
3) Loving the key facts box. Can we experiment with small increase in font for the content and a small increase of space between lines?

**Comment by Richenda** [comment]
4: We need alignment between the grey text boxes and the Key Facts box. The grey boxes should be stretched horizontally so they start at the left edge of the Key Facts box and end at the right edge of the map.
5: The 'connect' button looks better at the right end of the username. I think. My bad.

**Comment by Richenda** [comment]
6: Change the colour of the 'connect' button from purple to green. The medium green option.

**Comment by sebgrebe** [comment]
- [ ] Profile pic left
- [ ] Grey boxes paler
- [ ] font size key facts 
- [ ] align key facts and grey
- [ ] connect btn right of name
- [ ] Connect button medium green

**Comment by Manoj-nathwani** [comment]
Closing as this card is in the "Done" column on the project board
If any further work is needed, make a new card :)
