### ISSUE TITLE
Default Hub Avatars

### ISSUE THREAD

**Issue by Richenda** [rtcharity/hubreboot#61]
Here's a link for the stock images we should use for avatars (aka profile pictures) https://drive.google.com/drive/folders/1tUDZzlZF5whbcAvGgc2Mm8r3BVmK4gjf?usp=sharing
There are two categories: 'white' and 'colour'. If the space behind the picture will be white then we will use the coloured set. If the space behind is coloured we will use avatars that have the white fill.

I would like it if all Hub users are assigned one of these avatars randomly. They should then be given a choice in their user settings either to upload their own image OR to choose another stock avatar. In that section we will have all of these images (either all colour or all white) there for the users to pick from.

**Comment by Richenda** [comment]
One more thing... is it safe posting a publicly viewable google drive link here? I need to protect the art.

**Comment by sebgrebe** [comment]
@Richenda It's not if you don't want people to have access to it as the repo is public. However, once the site is up, anyone could download the pics anyway.

**Comment by michaltrzesimiech** [comment]
@Richenda can we close this now?
