### ISSUE TITLE
Group Section Wireframe

### ISSUE THREAD

**Issue by Richenda** [rtcharity/hubreboot#62]
![e8596393-16c9-482f-a483-75d842e12531](https://user-images.githubusercontent.com/14843012/50545939-e0db8a80-0bd3-11e9-9cd8-2de05e48fe9c.png)

**Comment by sebgrebe** [comment]
@richenda The "type" information (university vs local) is not stored in the database, so I can't add this to the table.

**Comment by Richenda** [comment]
@sebgrebe Yes but we need to change the database then to make it better. If not now then in a later release.

**Comment by Richenda** [comment]
Of course this will require updated data from LEAN but I can supply it.

**Comment by Richenda** [comment]
@Manoj-nathwani how hard is it to change the database?

**Comment by Manoj-nathwani** [comment]
@Richenda  We've got a shiny new tech-stack now, so we can do ANYTHING!!! 🎉 

To answer you questions, let's do a few things:
- Mark this card as complete as the wireframe are now integrated
- Figure out what fields we care about. You can see what's currently in the database [here](https://github.com/rtcharity/hubreboot/blob/master/groups/models.py#L8)
- Make a new card telling us which data from LEAN you want added to the site
- Make a new card telling us what data you want users to add to their profiles

Feel free to discuss any of this over slack :)
