### ISSUE TITLE
Make group avatar

### ISSUE THREAD

**Issue by sebgrebe** [rtcharity/hubreboot#66]
To implement https://github.com/rtcharity/hubreboot/issues/60, we need a group avatar.

**Comment by Richenda** [comment]
Here it is: https://drive.google.com/open?id=1n8EzcoIufqta-wu2_qpXgMEAdSq6zs8r 
To make it easy to find again, I put it in the same folder as the stock avatars for individual profiles. However the group one is in the main folder all on it's own while the personal profile avatars are all in a 'white' or 'colour' folder. https://drive.google.com/open?id=1tUDZzlZF5whbcAvGgc2Mm8r3BVmK4gjf
