### ISSUE TITLE
Add pages for groups and profiles maps

### ISSUE THREAD

**Issue by sebgrebe** [rtcharity/hubreboot#70]
* Paths: /maps/profiles and maps/groups
* Can be almost identical, only difference that toggle is set to inidividuals for /map/profiles and groups for map/groups
* Should be linked to on:
 * /groups
 * /profiles
 * /profile/id
 * /group/id (maybe?)
* Blocked until: wireframes done

**Comment by Manoj-nathwani** [comment]
Isn't this already how the following links work?
- https://eahub.azurewebsites.net/profiles
- https://eahub.azurewebsites.net/groups/

**Comment by sebgrebe** [comment]
@Manoj-nathwani The idea was that the maps are taken from those pages and onto individual ones. This hasn't been decided yet though. Waiting for Richenda's comment on [this](https://github.com/rtcharity/hubreboot/issues/55#issuecomment-452847992)

**Comment by sebgrebe** [comment]
abandoned in favour of having map on homepage
