### ISSUE TITLE
Delete lat/lon data for all Users as we don't need it and it's just asking for trouble.

### ISSUE THREAD

**Issue by Manoj-nathwani** [rtcharity/hubreboot#76]
# Problem
There's no need to store exact lat/lon data for each User, so let's just anonymise it by only storing their town/city rather than exact GPS coordinates. Keep them for Groups as it'll be nice to know the exact addresses of each meetup.

# Solution
- Look into how the charting on the site works to see if we can simply insert a town/city rather than lat/lon for Users
- Remove lat/lon from the database entirely as it's just asking for trouble

**Comment by Richenda** [comment]
Excellent.

The map on the old Hub got buggy so often.

**Comment by Manoj-nathwani** [comment]
Done ✅ 
https://github.com/rtcharity/hubreboot/commit/673e38757e8d8ba92772462d8ba2d5283e9b5433
