### ISSUE TITLE
Make development environment reproducible

### ISSUE THREAD

**Issue by taymonbeal** [rtcharity/hubreboot#8]
Contributors should be able to clone this repo and then easily bring up a copy of the EA Hub on their own development machines. This is a prerequisite for people being able to work independently on new features and improvements.

**Comment by taymonbeal** [comment]
Blocked on #10.

**Comment by taymonbeal** [comment]
Putting this on hiatus for now as it doesn't work with our current WordPress Customizer-based site design. Eventually we'll need to move away from that, but for the moment it's not blocking anything else.

**Comment by Manoj-nathwani** [comment]
This is now sorted!
Using the `.env` file we're now able to set the database name to whatever we want. So our production database is currently `eahub3` however `eahub` is still available and can be used to testing features which effects data without worrying about ruining our production data.
