### ISSUE TITLE
Allow users to edit group organisers

### ISSUE THREAD

**Issue by Manoj-nathwani** [rtcharity/hubreboot#83]

**Comment by michaltrzesimiech** [comment]
Removing donations from title.

**Comment by michaltrzesimiech** [comment]
@Richenda should we prioritize this prior to the launch on Monday?

**Comment by sebgrebe** [comment]
@michaltrzesimiech donations have been removed from group profiles.

**Comment by michaltrzesimiech** [comment]
@sebgrebe I meant this part: 

> Allow users to edit group organisers

**Comment by sebgrebe** [comment]
> @sebgrebe I meant this part:
> 
> > Allow users to edit group organisers

Ah ok, I see.

**Comment by Richenda** [comment]
> @Richenda should we prioritize this prior to the launch on Monday?

If it's doable.

**Comment by Manoj-nathwani** [comment]
Doesn't look feasible to do within 48hrs, but straight after yes, it's the next major feature i'll be working on.

**Comment by Richenda** [comment]
Ok no worries!

**Comment by taymonbeal** [comment]
Duplicate of #304.
