### ISSUE TITLE
Improve design by adding more padding and margins

### ISSUE THREAD

**Issue by sebgrebe** [rtcharity/hubreboot#84]
*problem*
all wireframes are made for small screens, so things like this look ugly

*solution*
can you make all page content stay within the `.container-narrow` class.

**Comment by Manoj-nathwani** [comment]
@sebgrebe don't worry about this, I'll sort all issues like this out when I do my big front-end cleanup
https://github.com/rtcharity/hubreboot/projects/2#card-16303167

**Comment by Manoj-nathwani** [comment]
@sebgrebe don't worry too much about this if it's a pain. I'll be doing my big ol font-end reshuffle anyway: https://github.com/rtcharity/hubreboot/projects/2#card-16303167

**Comment by sebgrebe** [comment]
@michaltrzesimiech obsolete.
