### ISSUE TITLE
Group profile model updates

### ISSUE THREAD

**Issue by Richenda** [rtcharity/hubreboot#86]
Having looked through this https://github.com/rtcharity/hubreboot/blob/master/groups/models.py#L8, here is my list of changes to make in the database for groups.

1) Collapse LEAN email and Official email. Just have one email field called 'group email'. If we have to decide between 2 email addresses, let me know and I'll make the call
2) Include a field for 'group type'. We can choose country, city or University as the types. I can add this data or we can leave it for users to fill in depending on what you think we have time for.
3) Include a field for total group donations. We don't have the data but will encourage organisers to add this.
4) Include field for frequency of group meetings per month. Call it 'approximate meetings per month'. People should be able to use text for the answer.
5) Field for group description. Organisers can fill this in giving a short blurb about their group.

**Comment by Manoj-nathwani** [comment]
# Done ✅ 
- I've removed `lean_email` in this update https://github.com/rtcharity/hubreboot/commit/e9957565ac4634c7248c16b6fe616dea87cb2d50
- In the database I combined both fields but only kept one email address

# Additional work needed by @Richenda 
- For groups who had both an `official_email` and `lean_email`, i've kept only the `official_email` and i've exported the data so you can manually fix it if you like. There's only 11 rows so it should be quick.
- Fix up the data in google sheets [here](https://rtcharity.slack.com/archives/GF1K33GAJ/p1548711004008500?thread_ts=1548711001.008300&cid=GF1K33GAJ) and let me know and i'll update the database accordingly.

**Comment by Manoj-nathwani** [comment]
@michaltrzesimiech this may be a quick thing for you to do actually ^

**Comment by Richenda** [comment]
Done!
