### ISSUE TITLE
Get a list with all the fields expected on: /profile

### ISSUE THREAD

**Issue by sebgrebe** [rtcharity/hubreboot#88]
We need to agree which fields (summary, donations, etc), we want to see on /profile. This probably needs to be a compromise between what we want (@richenda) and what can realistically be delivered (@Manoj-nathwani)

[Current example](https://eahub.azurewebsites.net/profile/5389)

**Comment by Manoj-nathwani** [comment]
Closing as it's a very old issue which we've solved
