### ISSUE TITLE
Feedback: /profiles

### ISSUE THREAD

**Issue by sebgrebe** [rtcharity/hubreboot#97]
[Link](https://eahub.azurewebsites.net/profiles)
I've made /profiles layout analogous to /groups.  
@Richenda  Put feedback into comments, if you have any

**Comment by Richenda** [comment]
@sebgrebe Looking great. Only things left is uploading more of the stock avatars and randomly distributing them across the users. At the moment there's just one that all users have.

The other thing is that when Manoj started out we had the EA Hub log and then we had /profiles or /groups afterwards. I think it actually worked really nicely and it's good for people to see which section they're in by looking at the header wherever they go. Is it straightforward to have that detail back again?

**Comment by sebgrebe** [comment]
Thanks @Richenda. Made tickets for these requests. 
Closing this ticket
